import type { WeeklyPlay } from "@/domain/play-card";

export const rehearsalPlays: WeeklyPlay[] = [
  {
    id: "w1-buf-nyj",
    season: 2026,
    week: 1,
    gameId: "rehearsal-buf-nyj",
    playType: "single",
    market: "spread",
    primaryReason: "model-price",
    pickedBy: "gabe",
    title: "Buffalo −2.5",
    legs: "Bills at Jets",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 3.4,
    estimatedEvPercent: 5.8,
    confidence: "best",
    statsCase: "Pressure-rate mismatch survives the market blend; translated BetMGM price is 2.1 cents better.",
    footballCase: "Confirm Buffalo's protection calls and receiver rotation before locking.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-10T18:20:00Z",
    updatedAt: "2026-09-10T18:20:00Z"
  },
  {
    id: "w1-mia-ne-under",
    season: 2026,
    week: 1,
    gameId: "rehearsal-mia-ne",
    playType: "single",
    market: "total",
    primaryReason: "weather",
    pickedBy: "jarrett",
    title: "Miami / New England under 44.5",
    legs: "Dolphins at Patriots",
    book: "FanDuel",
    americanOdds: -105,
    stakeCents: 5000,
    modelEdgePp: 2.2,
    estimatedEvPercent: 4.5,
    confidence: "play",
    statsCase: "Wind-sensitive pass rates and neutral-situation pace project 3.1 points below market.",
    footballCase: "Watch offensive-line continuity and whether New England can sustain drives.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-10T19:10:00Z",
    updatedAt: "2026-09-10T19:10:00Z"
  },
  {
    id: "w1-teaser-one",
    season: 2026,
    week: 1,
    gameId: "rehearsal-teaser",
    playType: "teaser",
    market: "teaser",
    primaryReason: "key-number",
    pickedBy: "gabe",
    title: "BUF +3.5 / GB +8.5",
    legs: "Two-team 6-point teaser",
    book: "BetMGM",
    americanOdds: -120,
    stakeCents: 5000,
    modelEdgePp: 2.6,
    estimatedEvPercent: 4.8,
    confidence: "play",
    statsCase: "Both legs cross 3 and 7; the joint win estimate clears the break-even rate by 2.6 points.",
    footballCase: "Avoid if either offensive line loses a starter in final inactives.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T01:05:00Z",
    updatedAt: "2026-09-11T01:05:00Z"
  },
  {
    id: "w1-parlay-one",
    season: 2026,
    week: 1,
    gameId: "rehearsal-parlay",
    playType: "parlay",
    market: "parlay",
    primaryReason: "model-price",
    pickedBy: "gabe",
    title: "DET ML / KC ML",
    legs: "Two-leg moneyline parlay",
    book: "FanDuel",
    americanOdds: 138,
    stakeCents: 5000,
    modelEdgePp: 2.1,
    estimatedEvPercent: 5.0,
    confidence: "lean",
    statsCase: "Correlation-adjusted joint probability remains above the offered price; no same-game dependence.",
    footballCase: "Need a clean read on Detroit's interior defense and Kansas City's receiver usage.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T02:40:00Z",
    updatedAt: "2026-09-11T02:40:00Z"
  },
  {
    id: "w1-lar-ari",
    season: 2026,
    week: 1,
    gameId: "rehearsal-lar-ari",
    playType: "single",
    market: "spread",
    primaryReason: "regression",
    pickedBy: "jarrett",
    title: "Arizona +4.5",
    legs: "Rams at Cardinals",
    book: "FanDuel",
    americanOdds: -108,
    stakeCents: 5000,
    modelEdgePp: 2.9,
    estimatedEvPercent: 5.4,
    confidence: "play",
    statsCase: "Explosive-play regression and opponent-adjusted early-down EPA make +4.5 the last playable number.",
    footballCase: "Check whether Arizona's young secondary communication holds up in preseason reports.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T03:15:00Z",
    updatedAt: "2026-09-11T03:15:00Z"
  },
  {
    id: "w1-den-ten-under",
    season: 2026,
    week: 1,
    gameId: "rehearsal-den-ten",
    playType: "single",
    market: "total",
    primaryReason: "pace-total",
    pickedBy: "gabe",
    title: "Denver / Tennessee under 42",
    legs: "Broncos at Titans",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 2.5,
    estimatedEvPercent: 4.8,
    confidence: "play",
    statsCase: "Both offenses rank in the bottom quartile of projected pace; red-zone efficiency is regressed toward league mean.",
    footballCase: "Quarterback comfort and scripted tempo are the swing factors.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T04:00:00Z",
    updatedAt: "2026-09-11T04:00:00Z"
  },
  {
    id: "w1-bal-ml",
    season: 2026,
    week: 1,
    gameId: "rehearsal-bal-cle",
    playType: "single",
    market: "moneyline",
    primaryReason: "key-number",
    pickedBy: "jarrett",
    title: "Baltimore moneyline",
    legs: "Ravens at Browns",
    book: "FanDuel",
    americanOdds: -135,
    stakeCents: 5000,
    modelEdgePp: 2.0,
    estimatedEvPercent: 3.5,
    confidence: "lean",
    statsCase: "The moneyline is more efficient than laying 2.5 after discrete margin translation.",
    footballCase: "Monitor Cleveland's pass-rush rotation; it determines whether the statistical edge is actionable.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T05:20:00Z",
    updatedAt: "2026-09-11T05:20:00Z"
  },
  {
    id: "w1-sea-sf-over",
    season: 2026,
    week: 1,
    gameId: "rehearsal-sea-sf",
    playType: "single",
    market: "total",
    primaryReason: "pace-total",
    pickedBy: "gabe",
    title: "Seattle / San Francisco over 45.5",
    legs: "49ers at Seahawks",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 1.8,
    estimatedEvPercent: 3.4,
    confidence: "lean",
    statsCase: "Explosive pass rate and pass-over-expectation point to more possessions than the market baseline.",
    footballCase: "This stays a lean until the Seahawks' offensive-line mix is confirmed.",
    executionStatus: "paper",
    cashPlacementConfirmed: false,
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T06:15:00Z",
    updatedAt: "2026-09-11T06:15:00Z"
  }
];
