import type { WeeklyPlay } from "@/domain/play-card";

export const rehearsalPlays: WeeklyPlay[] = [
  {
    id: "w1-buf-nyj",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Buffalo −2.5",
    legs: "Bills at Jets",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 3.4,
    estimatedEvPercent: 5.8,
    confidence: "best",
    statsCase: "Pressure-rate mismatch survives the market blend; translated BetMGM price is 2.1 cents better.",
    footballCase: "Confirm Buffalo's protection calls and receiver rotation before locking.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-10T18:20:00Z",
    updatedAt: "2026-09-10T18:20:00Z"
  },
  {
    id: "w1-mia-ne-under",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Miami / New England under 44.5",
    legs: "Dolphins at Patriots",
    book: "FanDuel",
    americanOdds: -105,
    stakeCents: 5000,
    modelEdgePp: 2.2,
    estimatedEvPercent: 4.5,
    confidence: "play",
    statsCase: "Wind-sensitive pass rates and neutral-situation pace project 3.1 points below market.",
    footballCase: "Watch offensive-line continuity and whether New England can sustain drives.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-10T19:10:00Z",
    updatedAt: "2026-09-10T19:10:00Z"
  },
  {
    id: "w1-teaser-one",
    season: 2026,
    week: 1,
    playType: "teaser",
    title: "BUF +3.5 / GB +8.5",
    legs: "Two-team 6-point teaser",
    book: "BetMGM",
    americanOdds: -120,
    stakeCents: 5000,
    modelEdgePp: 2.6,
    estimatedEvPercent: 4.8,
    confidence: "play",
    statsCase: "Both legs cross 3 and 7; the joint win estimate clears the break-even rate by 2.6 points.",
    footballCase: "Avoid if either offensive line loses a starter in final inactives.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T01:05:00Z",
    updatedAt: "2026-09-11T01:05:00Z"
  },
  {
    id: "w1-parlay-one",
    season: 2026,
    week: 1,
    playType: "parlay",
    title: "DET ML / KC ML",
    legs: "Two-leg moneyline parlay",
    book: "FanDuel",
    americanOdds: 138,
    stakeCents: 5000,
    modelEdgePp: 2.1,
    estimatedEvPercent: 5.0,
    confidence: "lean",
    statsCase: "Correlation-adjusted joint probability remains above the offered price; no same-game dependence.",
    footballCase: "Need a clean read on Detroit's interior defense and Kansas City's receiver usage.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T02:40:00Z",
    updatedAt: "2026-09-11T02:40:00Z"
  },
  {
    id: "w1-lar-ari",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Arizona +4.5",
    legs: "Rams at Cardinals",
    book: "FanDuel",
    americanOdds: -108,
    stakeCents: 5000,
    modelEdgePp: 2.9,
    estimatedEvPercent: 5.4,
    confidence: "play",
    statsCase: "Explosive-play regression and opponent-adjusted early-down EPA make +4.5 the last playable number.",
    footballCase: "Check whether Arizona's young secondary communication holds up in preseason reports.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T03:15:00Z",
    updatedAt: "2026-09-11T03:15:00Z"
  },
  {
    id: "w1-den-ten-under",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Denver / Tennessee under 42",
    legs: "Broncos at Titans",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 2.5,
    estimatedEvPercent: 4.8,
    confidence: "play",
    statsCase: "Both offenses rank in the bottom quartile of projected pace; red-zone efficiency is regressed toward league mean.",
    footballCase: "Quarterback comfort and scripted tempo are the swing factors.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T04:00:00Z",
    updatedAt: "2026-09-11T04:00:00Z"
  },
  {
    id: "w1-bal-ml",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Baltimore moneyline",
    legs: "Ravens at Browns",
    book: "FanDuel",
    americanOdds: -135,
    stakeCents: 5000,
    modelEdgePp: 2.0,
    estimatedEvPercent: 3.5,
    confidence: "lean",
    statsCase: "The moneyline is more efficient than laying 2.5 after discrete margin translation.",
    footballCase: "Monitor Cleveland's pass-rush rotation; it determines whether the statistical edge is actionable.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T05:20:00Z",
    updatedAt: "2026-09-11T05:20:00Z"
  },
  {
    id: "w1-sea-sf-over",
    season: 2026,
    week: 1,
    playType: "single",
    title: "Seattle / San Francisco over 45.5",
    legs: "49ers at Seahawks",
    book: "BetMGM",
    americanOdds: -110,
    stakeCents: 5000,
    modelEdgePp: 1.8,
    estimatedEvPercent: 3.4,
    confidence: "lean",
    statsCase: "Explosive pass rate and pass-over-expectation point to more possessions than the market baseline.",
    footballCase: "This stays a lean until the Seahawks' offensive-line mix is confirmed.",
    status: "card",
    result: "pending",
    profitCents: 0,
    closingClvCents: null,
    createdBy: "gabe",
    createdAt: "2026-09-11T06:15:00Z",
    updatedAt: "2026-09-11T06:15:00Z"
  }
];

export const researchSignals = [
  {
    grade: "A",
    title: "Early-down EPA mismatch",
    matchup: "Buffalo offense vs. New York defense",
    finding: "+0.11 EPA/play gap after opponent and garbage-time adjustment",
    sample: "Trailing 10 regular-season games · 1,142 snaps",
    source: "nflverse play-by-play · refreshed Tue 6:18 PT"
  },
  {
    grade: "B",
    title: "Wind suppresses explosive passes",
    matchup: "Miami at New England",
    finding: "Kickoff wind projects 18 mph; comparable games saw a 9% median drop in explosive pass rate",
    sample: "84 outdoor games since 2018 · wide uncertainty",
    source: "Open-Meteo + nflverse · kickoff-hour forecast"
  },
  {
    grade: "B",
    title: "Turnover luck regression",
    matchup: "Arizona vs. Los Angeles",
    finding: "Arizona's −7 turnover margin explains more of last year's record than stable down-to-down efficiency",
    sample: "Full 2025 season · descriptive, not causal",
    source: "nflverse team drives · completed season"
  },
  {
    grade: "C",
    title: "Personnel continuity watch",
    matchup: "Denver at Tennessee",
    finding: "Both lines enter Week 1 with new starters at two positions",
    sample: "Depth-chart observation · needs human confirmation",
    source: "Official team reports · awaiting final inactives"
  }
] as const;
