# Narrow lag-distance cache: pre-implementation assessment

The proposed late lag-distance-only cache is preferable to caching coordinates. No remaining mathematical blocker is evident in the stated narrow domain. This is static design readiness only: no source, tests, numerical calls or profiling were created or executed. Attribution and historical-capacity interpretation remain separate.

Keep `np.indices`, the observation-dependent first term, the original padded-shape expression, both FFTs, conjugate/product, all correlation checks, clipping, repeated sums and normalization unchanged and fresh. At the original late location, use the exact padded `(M,N)` tuple to retrieve the private distance matrix, or calculate the original lag expressions and `np.hypot(lags[0][:,None], lags[1])` on a miss. Do not change the lag cutoff, dtype, axis order, formula or layout. Only that matrix is retained; no probability, input grid, observation, transform, correlation or score enters the cache.

The exact `ScoreGrid` / exact float64 ndarray / two-dimensional positive shape bounded by256 domain, plus exact float64 observed ndarray of shape(2,), provides a defensible standalone fast-path boundary. It implies padded power-of-two dimensions no larger than512. Type/rank/dtype/shape guards must remain ordinary metadata inspection, not a new probability scan or target validator. Unsupported inputs call the original energy function; check unsupported grid type before reading its attributes so the guard does not add arbitrary property hooks. Direct invalid numerical values inside otherwise supported arrays must still reach the original arithmetic and named failures in their original order.

Use one explicitly owned two-entry FIFO: hits do not refresh insertion order, duplicate shape entries are impossible, and eviction/publication happen only after the originating energy call has completed successfully. A miss keeps its matrix local until the original final result and clamp are known to succeed. A failed call must not publish a new entry, evict an old entry or return a cached score. Calculate a miss only after the original correlation checks and normalization; front-loading the lag construction would change failure order. Retained matrices must be exact float64 C-contiguous arrays with private ownership and read-only access. The4-MiB bound is a conservative retained-distance-array cap; temporary geometry/FFT arrays and the full process still require separate measured peak-memory accounting.

The proposed domain's geometry is bounded finite integer-lag arithmetic, which supports preserving its bits across repeated shapes under the same pinned NumPy/runtime. A hit intentionally skips constructor/allocation work, so universal reproduction of allocation failures or arbitrary monkeypatched constructor behavior is not a meaningful promise. Unexpected failures in actual current-data operations or cache construction/publication must propagate without catch-and-retry. Fixed runtime/source identity, a private sequential owner and no mutable shared/global binding are necessary assumptions.

For scorer integration, a static copy of the original `research_score_metrics.score_forecast` with only its two energy bindings changed is a small reviewable boundary. Preserve every other statement, default flag, imported helper and error class. Wrap the input once in the existing `SkellamDistribution`, exactly as the accepted scorer does; do not wrap twice, call an original scorer and then recompute its energy, or share its per-score CDF cache across calls. A source/AST comparison should whitelist only the explicit geometry-owner parameter/binding and the two energy call changes. A distribution subclass alone cannot redirect the frozen metrics module's imported energy function.

The fixed saved-synthetic sequence must retain all40 complete scoring callbacks, original game IDs/observations/laws and effective flags. Root's supplied attribution says40 base calls use80×80 grids and22 doubled calls use160×160 grids. If that contract is reproduced, a fresh two-entry owner should produce62 energy invocations, two successful geometry misses and60 hits, with both cold costs charged. Verify these counts from actual calls; do not substitute them for calls. The40-score owner must be newly empty for each separately registered parity/timing sequence; no warmed parity cache may carry into a purported cold timing pass.

Required qualification is complete original-versus-candidate metric bytes and exact return/error behavior, not energy alone. Retain every actual metric body, law/input image and cache/FFT count before assertions. Include repeated same shape with changed probabilities/observations, base/double alternation, a third eligible shape for FIFO eviction, rectangular transpose distinctions, unsupported fallback, all three original energy failures, late failure without publication, and subsequent valid calls. Verify no input/geometry mutation, independent owner isolation, all62 fresh FFT pairs and current-data reductions, original double-grid discrepancy checks, and no changed CDF-cache lifetime. Synthetic law reconstruction for the fixed saved sequence must follow its accepted descriptor contract without fitting or changing science.

A passing result would establish only this explicit cache/scorer path on the fixed synthetic sequence. The supplied0.040165177-second conservative attribution ceiling includes mixed self time and is not a guaranteed removable cost. No speedup estimate, historical retry or capacity conclusion follows from this design assessment.

This note relies on the exact source pins in `numerical-contract-assessment.md` (SHA-256 `fa13c9ea7840d94b9da7f628122251a3db832e20b6c97bc0554f24336db596b8`). The narrower decision deliberately leaves coordinate caching and CRPS changes outside scope.
