# RF-COMP-07 root static review

No static source/test/fixture/driver blocker remains in the held implementation. Actual numerical and resource results are pending. Root read the complete candidate and all 25 independent test methods, numerical contract and attribution assessments, scope/fixture/numerical reviews, and full driver plus its final warning/failure-evidence changes. No candidate/tests/driver import, scientific probe or test execution occurred in this review.

Held candidate SHA4bc57604fe237cd407b66e59c84c6021f8ed68fe287ecb71cb6cecf5a8cdcb16; tests SHA7061193136611105e8b2479025e99d2c60f0a9d0db290639a6ef241447ac5355; scope SHA4170c944f5e3d02a9f176518661d6d6616141cad0f6aafc419bc8bc87b70979e; fixture SHA1b1730b099eed2dd84eeb97f65b89a162dc7c4c9fcd4f5472aeee8a5dcede3aa. Final driver SHA644d849b2ae0ee927205213ae100ba3370bdfcbad354ad401eee7867543ffea4,36051bytes.

Metadata-only AST comparison confirms the complete candidate score-helper body is identical to the original metrics score_forecast body. Its signature adds an explicit energy dependency, and the public wrapper constructs the current Skellam wrapper once. The energy change preserves original coordinate/observation arithmetic, FFT calls, clipping/normalization/error checks, final score arithmetic and clamp. Only late shape-only distance matrices are retained. Unsupported exact-type/dtype/shape cases use the original fallback before new hooks. FIFO ownership, late miss publication, failed-call non-eviction, input independence and the retained-array byte ceiling are covered by focused tests; no full process-memory guarantee follows from that cache bound.

The fixed fixture authenticates all40 actual saved callback records in order, one lossless saved law and four complete metric bodies. It removes only the four named outer interval-mass fields computed after callbacks. All40 calls still recompute their full metrics. One shared synthetic law and two game IDs make this a favorable screening case; independent varied/invalid-input tests supply broader behavior checks, not historical timing coverage.

The driver executes the25 tests once, then40 original and40 candidate parity calls using a fresh owner. Parity-only sys.setprofile records real NumPy FFT implementation calls and validates their pinned source/decorator anchor; it never replaces shared numerical functions. Both routes must show62 real FFT pairs and80/160 grids. A second empty owner is constructed for the sole candidate timing pass. Original40 then candidate40 timing is fixed, with owner setup added to candidate aggregate; timers cover full Skellam/scorer/cache work. No profiler is attached during timing. Required exact full metric bytes, types/bits, warnings and input immutability precede materiality interpretation. Both aggregate and maximum callback ratios must be <=0.7738077598151377; a miss is a completed negative experiment rather than an invitation to retime.

The independent review's failure-retention issue is repaired: callback outcome/timing/warnings are saved before post-call input imaging, and typed actual results are saved before strict JSON conversion. Secondary imaging/serialization/evidence errors remain separately recorded without replacing a primary callback error. Actual budget exhaustion or storage failures still limit what can be retained; no universal persistence promise is made.

Parent/child use the accepted watchdog,60second/1024MiB command envelope,128/896MiB split and5second evidence reserve. Initial parent interpreter startup exclusion and sampled/waited RSS limitations are explicit. Before/after authentication includes all79 original sources, seven inherited runtime files, new code/fixture/assessments and numerical runtime dependencies. Root pin builder now includes the driver's copy.py,ast.py,warnings.py requirements and additional test/runtime files. Evidence bodies are deduplicated by bytes, each logical call retains its own observations, and independent reviews will be outside the sealed attempt.

Proceed only after the final independent driver review and exclusive pin freeze, implementation receipt and current quality check. The smallest next decision-changing action is the sole registered test. No historical invocation, controller integration, predictive acceptance or public research release is authorized by this readiness review.
