# RF-COMP-07 scope and materiality review

Read-only scope review, SHA `33be8280d52dc60fc2f5be0198433e8a17e361d3ff16ca9a494e79a73113d959`, against retained attribution-assessment.md and lag-distance-contract.md. No candidate/test/harness import, implementation, numerical execution or experiment. This is not final source/driver qualification.

The fixed complete40-callback panel is a useful and fair standalone screen: it retains36 inner/four outer original calls, laws/IDs/observations/flags and complete metrics, excludes copied64-grid rows, and charges original wrapper/scorer/double-grid work. A fresh empty owner for candidate parity and another fresh empty owner for timing prevents parity warming the measured cache. Original40 then candidate40 is fixed; both cold fills and all lookups belong to callback timings, with owner creation additionally charged to candidate aggregate. Two sizes/62 energy occurrences must be observed, not assumed from the earlier source-derived shapes. Keeping probability/observation work fresh and limiting retention to two private matrices is proportionate to the hypothesis.

Requiring BOTH aggregate and maximum callback ratios to satisfy the predeclared0.7738077598151377 screen is stricter and more useful than accepting any tiny speed improvement. Do not combine the retained bank helper, fit savings or old profiling shares. The loose0.040165177-second residual is explicitly not a removable-cost estimate. Either failing materiality screen defers/removes the candidate even if exactness passes; a passing tiny-panel screen is only an integration lead, not evidence that historical maxima or the7200-second pilot will pass.

One small definition to make explicit before driver freeze: whether equality exactly at0.7738077598151377 passes. The request describes a strict proxy; implement and record ratio<threshold for both aggregate and maximum (or document the intended inclusive rule before observing results). Do not choose the boundary after timing. Compute maximum from all40 individual callback intervals per route; add owner construction only to candidate aggregate as scoped. Retain all observations and any cold maximum/outlier without correction for order or OS effects.

Implementation acceptance assertions still needed: authenticate every per-call law body/reference and original callback ordering; enumerate the four post-callback interval-mass field names explicitly and remove no other diagnostics; retain original/candidate metric bodies and errors before assertions; verify fresh FFT pairs/cache fills/hits independently of expected counters. Unique stored input bodies are appropriate, but no cross-game metric reuse or prewarmed owner. Exact full-metric parity must precede timing interpretation.

The60-second/1024-MiB setup-inclusive observer plan with128/896 split and5-second reserve is consistent with the existing bounded qualification pattern. Actual fixture reconstruction/tests/scorer work, evidence writes and post-pin checks must fit this envelope; it is not guaranteed by the plan. Required input/runtime pins and static scorer-body equivalence remain to qualify. No new generalized framework, persisted cache, controller copy or public research work is justified. No other material scope blocker found.

Resolved before execution: verified revised scope SHA `4170c944f5e3d02a9f176518661d6d6616141cad0f6aafc419bc8bc87b70979e` and lines142–145. Both candidate/original aggregate (including owner construction) and maximum callback ratios use <=0.7738077598151377; equality explicitly passes. This resolves the sole scope clarification. One read-only text locator used the superseded wording and failed, then the exact revised lines were inspected; no candidate or timing execution occurred.
