# RF-COMP-07 saved scoring fixture review

Status: accepted metadata fixture within its fixed synthetic scope. Read builder source and independently checked its actual output using JSON/struct/hash arithmetic only; did not execute the builder or import NumPy/project/model code, reconstruct live distributions, score or run tests.

Fixture SHA `1b1730b099eed2dd84eeb97f65b89a162dc7c4c9fcd4f5472aeee8a5dcede3aa`. Authenticated source witness SHA `e695fcbcfc6f1c03754e1186c344cdc42bfa4cc45575ff517ecc4703f75f4db2` and its pointer against accepted index `ffd0946f89948226066ef95e56d5dc76a5ee85ce739fbfbddf5e004f24720e5b`. Every one of40 calls matches the original callback order and unique stage/setting-or-variant/game key, including complete callback record, flags, game ID and observed(21,17). Population is36 inner/four outer;22 doubled andfour diagnostic callbacks imply62 energy calls, still to be observed by actual qualification.

Independently matched each referenced law body to the corresponding saved resolved law and each metric body to its saved row using exact canonical metadata bytes. Exactly one complete law andfour distinct metric dictionaries (28/104 fields) are deduplicated by full body SHA. Only home_interval_mass_80,away_interval_mass_80,margin_interval_mass_80,total_interval_mass_80 are excluded, and only from outer rows. Those were post-callback fields. Game-specific metrics/IDs remain bound; bodies are not generic templates.

All four saved array images have exact<f8 dtype,finite float leaves,shape/product consistency and read-only flags; independent struct.pack little-endian verification matches every C-order byte. Beta binary64 big-endian bits and integer/bool scalar types agree. Later reconstruction must use saved bytes/scalar bits, independent contiguous arrays with the recorded read-only state, never fit or infer a new distribution. Original live aliases/strides are unavailable and are not claimed recovered.

The single identical law and two synthetic IDs with the same observed pair are deliberately favorable to repeated geometry. They do not represent historical law/observation diversity or establish capacity. The cache qualification must preserve fresh grids/probability transforms and full per-call outputs despite this repetition; independent adversarial tests remain necessary for varying inputs/shapes and failures. Source-derived80/160 grids,62 FFT pairs andtwo fills/60hits must be checked in the actual run. No controller integration, historical restart or scientific acceptance follows. No material fixture blocker found.
