# RF-COMP-05 static numerical readiness review

Decision: accepted for the single registered qualification, with no static blocker found. This is source review only; observed byte/error parity, timing, resource use and actual qualification remain pending. No candidate/test imports, test execution, serializer calls or scientific work were performed for this review. Reviewer authored the independent test file and discloses that scope; the candidate and qualification driver have other authors.

Reviewed immutable candidates:

- Candidate `scripts/research_score_strict_compute.py`: `87bfff865b0626ec05569a49e6c7935106b12f87ca222cf8ab5d7251edf97523`.
- Tests `tests/research-score-strict-compute/test_strict_compute.py`: `0ed92cbf7c902a9718e28bfb732c90a547945b8d1eddbe5850db775c6463a935`, 28 unittest methods, 435 lines.
- Scope `RF-COMP-05-STRICT-SCOPE.v1.md`: `e734420782264bfdf4dc80ec784c5e7cc05b2cab7a1836628cc77243fe74e344`.
- Design `NEXT-SERIALIZER-DESIGN.md`: `5d791b4e3aeea1bb001087b6185d9f0769ddaabec28fdbbe0829e16b1b6d329b`.

The original strict function is exactly `encoded(canonical(value))`. The candidate directly imports the unchanged `research_score_conditional_replay.canonical` and `research_score_contract.encoded`; it invokes canonical once, checks the resulting snapshot, and passes that same snapshot directly to original encoded on ineligibility. It retains no input/output cache, changes no process limits and has no retry or catch-and-fallback after the fast path begins. Canonical's existing NumPy/container conversion and raw traversal failures therefore remain the first boundary.

The compact encoder keeps the pinned stdlib token generation with sorted keys, ASCII escaping, finite values and compact separators. The formatter recognizes a complete quoted token before punctuation, copies scalar/string tokens unchanged, and adds only indent-two whitespace around nonempty containers, commas and colons. Empty containers retain their compact spelling; nesting supplies closing indentation, and strict adds one final newline and UTF-8 encoding. Escaped quotes/backslashes, punctuation within strings and signed-zero numeric tokens are preserved by construction. This reasoning is limited to valid compact JSON produced inside the fixed eligible domain; `_pretty` is not a general external-input JSON parser.

Eligibility uses exact built-in types, finite floats, integer bit length at most 256, root-container depth one through 32, at most 131,072 root/value/key occurrences and at most 4,194,304 Unicode characters across string occurrences. It rejects subclasses before calling their hooks. Active ancestors distinguish cycles from shared acyclic children; shared occurrences are revisited and counted. Guard state is fresh on each call. Unsupported values delegate to the original encoder, including its existing exceptions. Unexpected compact/format errors propagate unchanged.

The 28 independently expected test methods compare complete original/candidate bytes and exact exception class identity/message. They cover token/empty/nested layout, Unicode and lone surrogates, escape punctuation, finite extremes/subnormals/signed zero, integer and process decimal limits, nonfinite and unsupported values/keys, NumPy scalar/object/noncontiguous/read-only arrays, subclasses and separately constructed single-call hook counters, raw cycles and deep traversal, shared occurrences and each exact guard boundary, mutations/replacements, and failure followed by success. Eligibility expectations are independently specified; side-effecting cases use separate equivalent input objects and explicit snapshots rather than recanonicalizing the tested raw object. The four array-mutation rows label their known canonical-domain eligibility; the dedicated guard and NumPy tests exercise the actual helper separately.

Injected errors/spies patch only candidate-local names (`canonical`, `encoded`, `dumps`, `_pretty`) inside scoped context managers. They neither patch the frozen origin modules nor mutate shared json/NumPy bindings. Tests require one conversion/direct fallback, no encoder calls from eligibility, and propagation without retry. Actual output/error observations are emitted before parity assertions through `set_observation_writer`; guard-only and deliberate injection observations are distinguished from parity comparisons. Streaming retention keeps large boundary outputs out of the default observation list when the driver supplies its writer.

Limits: static review is not actual parity or performance evidence. Raw recursion/error wording and all hook behaviors still require the frozen runtime's observed qualification. The one fixed-order eleven-input timing pass cannot establish reliable historical speedup. This review authorizes no controller integration, historical invocation, frozen-source edit, or change to the existing scientific/resource gates.
