packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260811.1'

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  vinext@1.0.0-beta.2: patches/vinext@1.0.0-beta.2.patch
