// @vitest-environment jsdom
import React from 'react';import {afterEach,describe,it,expect} from 'vitest';import {render,screen,fireEvent,cleanup} from '@testing-library/react';import {BoardView,PointsAxis,ErrorAxis} from '../src/components/board-v7';import {position,sortGames,type BoardEvidence,type GameEvidence} from '../src/domain/board-v7';import type {ProjectionCardData,ProjectionBoardData} from '../src/domain/projection';
Object.defineProperty(window,'matchMedia',{value:()=>({matches:true})});
afterEach(cleanup);
const p={away_points:20.25,home_points:30,margin:9.75,total:50.25,home_win_probability:.7,away_win_probability:.3,intervals:{margin:{'50':[0,15],'80':[-5,25]},total:{'50':[40,60],'80':[30,70]}}};
const game={game_id:'final',away:'BAL',home:'IND',week:1,season:2026,kickoff_at:'2026-09-10T20:00:00Z',cutoff_at:'2026-09-10T18:45:00Z',issued_at:'2026-09-09T20:00:00Z',freeze_time:'2026-09-10T18:45:00Z',status:'FINAL',evidence:'AS_ISSUED',projection:p,final:{away_points:25,home_points:50},team_colors:{BAL:'#241773',IND:'#002C5F'},contributions:{away:[],home:[]},version:'v7',why:{lines:[],against:'Against:'}} as unknown as ProjectionCardData;
const e:GameEvidence={qualified_lock:true,teams:{away:{expected:20.25,actual:25,error:4.75,intervals:{'50':[15,25],'80':[10,30]},hits:{'50':true,'80':true},pit:.7},home:{expected:30,actual:50,error:20,intervals:{'50':[25,35],'80':[20,40]},hits:{'50':false,'80':false},pit:1}}};
const upcoming={...game,game_id:'upcoming',status:'UPCOMING',final:undefined,freeze_time:null} as ProjectionCardData;const missed={...upcoming,game_id:'missed',status:'MISSED',projection:null} as ProjectionCardData;
const board={default_week:1,games:[game,upcoming,missed]} as ProjectionBoardData;const ev={games:{final:e},trust:{inside80:1,eligible80:2}} as unknown as BoardEvidence;
describe('BOARD v7 contract',()=>{
 it('maps exact unrounded values and clips at axes',()=>{expect(position(20.25,'POINTS')).toBe(45);expect(position(-10,'ERROR')).toBeCloseTo(100/3);expect(position(50,'POINTS')).toBe(100)});
 it('renders original positions and separates observed ring',()=>{const {container}=render(<PointsAxis g={game} e={e}/>);expect((container.querySelector('[data-value="20.25"]') as HTMLElement).style.left).toBe('45%');expect(container.querySelectorAll('.v7-ring')).toHaveLength(2);expect(container.querySelectorAll('.outside')).toHaveLength(1)});
 it('keeps outside error beyond its outer band',()=>{const {container}=render(<ErrorAxis g={game} e={e}/>);const lane=container.querySelectorAll('.v7-error-lane')[1];const dot=lane.querySelector('.v7-dot') as HTMLElement;const band=lane.querySelector('[data-band="80"]') as HTMLElement;expect(parseFloat(dot.style.left)).toBeGreaterThan(parseFloat(band.style.left)+parseFloat(band.style.width))});
 it('does not change lens on rerender and preserves identities and colors',()=>{const r=render(<BoardView board={board} evidence={ev}/>);expect(r.container.querySelectorAll('.v7-detail')).toHaveLength(0);expect(screen.queryByText('Football WHY')).toBeNull();const rows=[...r.container.querySelectorAll('article')];fireEvent.click(screen.getByRole('button',{name:'ERROR'}));r.rerender(<BoardView board={{...board}} evidence={ev}/>);expect(screen.getByRole('button',{name:'ERROR'}).getAttribute('aria-pressed')).toBe('true');expect([...r.container.querySelectorAll('article')]).toEqual(rows);expect(screen.getByText('not played')).toBeTruthy();expect(screen.getAllByText('no lock').length).toBeGreaterThan(0);expect(screen.getByText('1 of 2 inside 80%')).toBeTruthy();fireEvent.click(r.container.querySelectorAll('.v7-row')[0]);expect(r.container.querySelector('.v7-detail [data-axis="POINTS"]')).toBeTruthy();fireEvent.click(r.container.querySelectorAll('.v7-row')[1]);expect(r.container.querySelectorAll('.v7-detail')).toHaveLength(1)});
 it('sorts both unknowns last in both directions',()=>{for(const order of ['ascending','descending'])expect(sortGames([missed,upcoming,game],{final:e},order).map(g=>g.game_id)).toEqual(['final','missed','upcoming'])});
 it('disables sorting without a final',()=>{render(<BoardView board={{...board,games:[upcoming]}} evidence={ev}/>);expect(screen.getByLabelText('Sort games').hasAttribute('disabled')).toBe(true)});
 it('contains no forbidden or decimal text',()=>{const {container}=render(<BoardView board={board} evidence={ev}/>);for(const lens of ['POINTS','ERROR']){fireEvent.click(screen.getByRole('button',{name:lens}));expect(container.textContent).not.toMatch(/\d+\.\d+|coin flip|\b(?:odds|EV|PLAY|PASS|TEASE|Gabe|Jarrett|FanDuel|BetMGM|Caesars|DraftKings)\b/i)}});
});
it('enforces integer display in expanded view',()=>{const {container}=render(<BoardView board={board} evidence={ev}/>);fireEvent.click(container.querySelector('.v7-row')!);expect(container.textContent).not.toMatch(/\d+\.\d+/);expect(screen.getByText('Football WHY')).toBeTruthy()});
