// @vitest-environment jsdom
import React from 'react';
import {afterEach,expect,it,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {ProjectionCard,PointsBar} from '../src/components/projection-card';
import {ProjectionRows} from '../src/components/projection-board';
import {pointShare} from '../src/components/board-v4-format';
import type {ProjectionCardData} from '../src/domain/projection';
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const p:NonNullable<ProjectionCardData['projection']>={home_points:22.49,away_points:24.12,margin:-1.63,total:46.61,home_win_probability:.45,away_win_probability:.55,tie_probability:.01,intervals:{margin:{'50':[-3.5,7.8],'80':[-9.7,18.2]},total:{'50':[35.5,50.3],'80':[28.7,60.1]}}};
const g={game_id:'test',season:2026,week:1,home:'IND',away:'BAL',kickoff_at:'2026-09-13T17:00:00Z',cutoff_at:'2026-09-13T15:45:00Z',issued_at:'2026-09-12T10:00:00Z',version:'projection-v3-test',status:'UPCOMING',evidence:'AS_ISSUED',projection:p,display:p,ours:null,winner:'BAL',winner_probability:.55,source:'PROJECTION',team_colors:{BAL:'#241773',IND:'#002c5f'},why:{lines:['Measured offense 2.35 adds 1.85 points.'],against:'Against: rest removes 0.65 points.'},contributions:{away:[{input:'roll',label:'Roll index',points:1.23,value:.75,status:'ACTIVE',source_hashes:[],weight:.5}],home:[]},trajectory:{home:[{season:2026,week:1,for:2.31,against:1.79,roll:.59}],away:[]},sheet:{'4':{name:'Efficiency',data_window:'2025 REG',teams:{IND:{points_per_drive:2.39}}}},grades:null} as unknown as ProjectionCardData;
it('unmounts all analysis from a collapsed row',()=>{const {container}=render(<ProjectionCard g={g}/>);expect(container.textContent).not.toMatch(/Against:|Measured offense|WINNER|projection-v3/);expect(container.querySelector('.b4-analysis')).toBeNull();expect(container.querySelector('.b4-bar')?.textContent).toBe('BAL 24IND 22');});
it('all expanded displayed numbers and edit values are integers without mutating data',()=>{const saved=JSON.stringify(g);const {container}=render(<ProjectionCard g={g} expanded/>);expect(container.textContent).not.toMatch(/\d\.\d/);for(const el of container.querySelectorAll('input[type=number]'))expect((el as HTMLInputElement).value).not.toMatch(/\./);expect(JSON.stringify(g)).toBe(saved);});
it('has one expanded row, closes it on second tap, and removes the previous WHY',()=>{const {container}=render(<ProjectionRows games={[g,{...g,game_id:'second',home:'SEA'}]}/>);const rows=container.querySelectorAll('.b4-row');fireEvent.click(rows[0]);expect(container.querySelectorAll('.b4-analysis')).toHaveLength(1);fireEvent.click(rows[1]);expect(container.querySelectorAll('.b4-analysis')).toHaveLength(1);expect(rows[0].getAttribute('aria-expanded')).toBe('false');expect(rows[1].getAttribute('aria-expanded')).toBe('true');fireEvent.click(rows[1]);expect(screen.queryByText('Football WHY')).toBeNull();});
it('FINAL uses actual points and a projected ghost with errors instead of probability',()=>{const {container}=render(<ProjectionCard g={{...g,status:'FINAL',final:{away_points:17,home_points:30},grades:{PROJECTION:{actual:{},errors:{margin:14.63,total:.39},interval_hits:{margin:{'50':false,'80':true},total:{'50':true,'80':true}}}}}}/>);expect(container.querySelector('.b4-bar')?.textContent).toBe('BAL 17IND 30');expect(container.querySelector('.b4-ghost')).not.toBeNull();expect(container.querySelector('.b4-result')?.textContent).toContain('Margin error 15');expect(container.querySelector('.b4-result')?.textContent).not.toContain('%');});
it('uses our score and keeps the original split; point proportions sum exactly',()=>{const {container}=render(<PointsBar g={{...g,ours:{...p,away_points:28.7,home_points:20.1}}}/>);const segments=container.querySelectorAll<HTMLElement>('.b4-segment');expect(parseFloat(segments[0].style.width)+parseFloat(segments[1].style.width)).toBeCloseTo(100,12);expect(container.querySelector('.b4-ghost')).not.toBeNull();expect(pointShare(0,0)).toBe(.5);expect(pointShare(0,20)).toBe(0);});

it('saving untouched rounded score fields preserves their full precision',async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,json:async()=>({})});vi.stubGlobal('fetch',fetcher);const {container}=render(<ProjectionCard g={g} expanded/>);fireEvent.submit(container.querySelector('form')!);await waitFor(()=>expect(fetcher).toHaveBeenCalled());const body=JSON.parse(fetcher.mock.calls[0][1].body);expect(body.away_points).toBe(p.away_points);expect(body.home_points).toBe(p.home_points);});
