// @vitest-environment jsdom
import React from 'react';import {afterEach,it,expect} from 'vitest';import {cleanup,render,screen,fireEvent} from '@testing-library/react';
import {BoardViewV9,MatchupV9} from '../src/components/board-v9';import {scoreContext,ordinal,type ContextData} from '../src/domain/board-v9';import {board,evidence,final,upcoming} from './board-v8-fixture';
afterEach(cleanup);
import {context} from './board-v9-fixture';

it('removes comparison content in collapsed, expanded and ERROR states',()=>{const polluted={...final,why:{lines:['BETMGM OVER 50 covered the line','Measured run game adds 2 points'],against:'Against: UNDER at FanDuel'},sheet:{a:{name:'DraftKings line',teams:{},data_window:''}}};const {container}=render(<BoardViewV9 board={{...board,games:[polluted,upcoming]}} evidence={evidence} context={context}/>);const check=()=>expect(container.textContent).not.toMatch(/\b(betmgm|caesars|fanduel|draftkings|pinnacle|book|line|cover|covered|over|under|disagreement|lean)\b/i);check();expect(container.querySelectorAll('[role="columnheader"]')).toHaveLength(6);fireEvent.click(screen.getByRole('button',{name:'SF at LA'}));check();expect(screen.getByText('Football WHY')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'ERROR'}));check();fireEvent.click(screen.getByRole('button',{name:'DET at BUF'}));check();expect(screen.getAllByText('Football WHY')).toHaveLength(1);});
it('marks upcoming projected winner separately from actual winner with home bottom',()=>{const {container,rerender}=render(<MatchupV9 g={upcoming}/>);expect(container.querySelectorAll('[data-side]')[1].getAttribute('data-side')).toBe('home');expect(container.querySelectorAll('.v9-winner-dot')).toHaveLength(1);expect(container.querySelector('[data-team="BUF"]')?.className).toContain('projected');expect(container.querySelector('[data-team="DET"]')?.className).not.toContain('projected');rerender(<MatchupV9 g={final}/>);expect(container.querySelector('[data-team="SF"]')?.className).toContain('actual');expect(container.querySelector('[data-team="SF"]')?.className).not.toContain('projected');expect(container.querySelector('[data-team="LA"]')?.className).toContain('projected');});
it('uses the precise engine total interval and highlights the matching score',()=>{const g={...final,projection:{...final.projection!,intervals:{...final.projection!.intervals,total:{'50':[43.2,53.8] as [number,number],'80':[30,70] as [number,number]}}}};const {container}=render(<BoardViewV9 board={{...board,games:[g]}} evidence={evidence} context={context}/>);expect(screen.getByLabelText('Total points 50% predictive interval').textContent).toBe('(43–54)');expect(container.querySelector('[data-score-team="LA"]')?.className).toBe('winning-score');expect(container.querySelector('[data-score-team="SF"]')?.className).toBe('losing-score');expect(container.textContent).toContain('SF +3, LA -19');expect(container.textContent).toContain('SF in 50% · LA outside 80%');});
it('flags prior-season context and rejects mismatched version, points or issuance',()=>{render(<BoardViewV9 board={{...board,games:[final]}} evidence={evidence} context={context}/>);expect(screen.getAllByText(/2025 · 17 games · prior season/)).toHaveLength(2);expect(screen.getByText('72nd · league, 14 games')).toBeTruthy();for(const changed of [{...final,version:'different'},{...final,issued_at:'later'},{...final,ours:{...final.projection!,home_points:99}}])expect(scoreContext(changed,context)).toBeUndefined();});
it('ties have no projected dot and missing history has a named shortfall',()=>{const g={...upcoming,projection:{...upcoming.projection!,home_points:24,away_points:24,margin:0}};const {container}=render(<BoardViewV9 board={{...board,games:[g]}} evidence={evidence} context={null}/>);expect(container.querySelector('.v9-winner-dot')).toBeNull();expect(container.textContent).toContain('Needs scoring history at issuance');expect([ordinal(1),ordinal(2),ordinal(11),ordinal(12),ordinal(13),ordinal(21)]).toEqual(['1st','2nd','11th','12th','13th','21st']);});
