// @vitest-environment jsdom
import React from 'react';import {afterEach,it,expect} from 'vitest';import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {BoardViewV8,Matchup,Disagreement} from '../src/components/board-v8';import {bar,comparison,outcome,qualifyingBook} from '../src/domain/board-v8-market';import {board,evidence,books,final,quote} from './board-v8-fixture';
afterEach(cleanup);
it('maps signed full precision disagreement at six pixels per point and clips',()=>{expect(bar(-2.5)).toEqual({width:15,left:33,strong:true});expect(bar(1.9)).toEqual({width:11.399999999999999,left:48,strong:false});expect(bar(12).width).toBe(48);expect(comparison(final,quote)).toEqual({side:-2,total:1.5});});
it('uses white exactly at two and muted at 1.9 without rounding geometry',()=>{const {container,rerender}=render(<Disagreement gap={2}/>);expect(container.querySelector('[data-strong]')?.getAttribute('data-strong')).toBe('true');rerender(<Disagreement gap={1.9}/>);expect(container.querySelector('[data-strong]')?.getAttribute('data-strong')).toBe('false');});
it('keeps independent projected bold and observed chip, including tie and no lock',()=>{const {container,rerender}=render(<Matchup g={final} e={evidence.games.final}/>);expect(container.querySelector('[data-team="LA"]')?.classList.contains('predicted')).toBe(true);expect(container.querySelector('[data-team="SF"]')?.classList.contains('actual')).toBe(true);expect(container.querySelector('[data-team="SF"]')?.classList.contains('predicted')).toBe(false);rerender(<Matchup g={{...final,final:{home_points:7,away_points:7}}} e={{...evidence.games.final,qualified_lock:false}}/>);expect(container.querySelector('.actual')).toBeNull();expect(container.querySelector('.predicted')).toBeNull();});
it('has no WHY collapsed, expands only one, and lenses preserve order and IDs',()=>{const {container}=render(<BoardViewV8 board={board} evidence={evidence} books={books}/>);const ids=()=>Array.from(container.querySelectorAll('[data-game-id]')).map(x=>x.getAttribute('data-game-id'));const before=ids();expect(container.textContent).not.toContain('Football WHY');fireEvent.click(screen.getByRole('button',{name:'SF at LA'}));expect(screen.getAllByText('Football WHY')).toHaveLength(1);expect(container.querySelectorAll('[data-quantile]')).toHaveLength(20);fireEvent.click(screen.getByRole('button',{name:'DET at BUF'}));expect(screen.getAllByText('Football WHY')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'ERROR'}));expect(ids()).toEqual(before);expect(container.textContent).toContain('not played');fireEvent.click(screen.getByRole('button',{name:'SCORES'}));expect(ids()).toEqual(before);expect(container.textContent).not.toMatch(/coin flip|Gabe|Jarrett|Josh Allen/);expect(container.querySelector('.v8-kickoff')?.textContent).toContain('ET');});
it('missing book preserves scores with dashes in both book/lean cells',()=>{const {container}=render(<BoardViewV8 board={board} evidence={evidence} books={books}/>);const row=container.querySelector('[data-game-id="missing"]')!;expect(Array.from(row.querySelectorAll('.v8-desktop .book')).map(x=>x.textContent)).toEqual(['—','—']);expect(Array.from(row.querySelectorAll('.v8-desktop .v8-lean')).map(x=>x.textContent)).toEqual(['—','—']);expect(row.textContent).toContain('24–26');});
it('settles only against prelock quoted lines and handles pushes',()=>{expect(outcome(final,quote)).toBe('SF covered · UNDER 34');expect(outcome({...final,final:{home_points:26,away_points:22}},{...quote,total:48})).toBe('SPREAD PUSH · TOTAL PUSH 48');expect(qualifyingBook(final,{...quote,captured_at:final.cutoff_at})).toBeUndefined();});
it('both lean cells use full precision at 2 and 1.9',()=>{const g={...final,projection:{...final.projection!,margin:5.9,total:50.4}};const {container,rerender}=render(<BoardViewV8 board={{...board,games:[g]}} evidence={evidence} books={books}/>);expect(Array.from(container.querySelectorAll('.v8-desktop .v8-lean')).every(x=>x.getAttribute('data-strong')==='false')).toBe(true);g.projection.margin=6;g.projection.total=50.5;rerender(<BoardViewV8 board={{...board,games:[g]}} evidence={evidence} books={books}/>);expect(Array.from(container.querySelectorAll('.v8-desktop .v8-lean')).every(x=>x.getAttribute('data-strong')==='true')).toBe(true);});

it('applies both mechanisms to the same winner on agreement',()=>{const {container}=render(<Matchup g={{...final,final:{home_points:30,away_points:20}}} e={evidence.games.final}/>);expect(container.querySelector('[data-team="LA"]')?.className).toContain('predicted actual');});
