import {it,expect,vi,afterEach} from 'vitest';
import {readProjection,readProjectionRaw,projectionResponse,refreshProjection} from '../src/server/projection-board';
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
const raw='{\n "schema":"projection-board-v1", "published_at":"2026-09-13T20:00:00Z", "example":13.0, "small":1e-06, "label":"é", "games":[{"game_id":"missing","status":"MISSED","projection":null}]\n}\n';
const board=JSON.parse(raw);
function db(checked_at:number,legacy=false,failWrite=false){
 const rows=new Map([[legacy?1:2,{payload:legacy?JSON.stringify(board):raw,checked_at}]]);
 const run=vi.fn();const prepare=vi.fn((sql:string)=>({bind:(...args:unknown[])=>({first:async()=>rows.get(args[0] as number)??null,run:async()=>{run(...args);if(failWrite)throw Error('write failed');if(sql.startsWith('INSERT')&&Number(args[2])>=(rows.get(args[0] as number)?.checked_at??0))rows.set(args[0] as number,{payload:args[1] as string,checked_at:args[2] as number});}})}));
 return {prepare,run,rows};
}
const served=(text=raw,status=200)=>new Response(text,{status});
it('preserves exact source text through HTTP, cold cache and warm cache',async()=>{const fetcher=vi.fn().mockImplementation(async()=>served());vi.stubGlobal('fetch',fetcher);const cache=db(0);expect(await (await projectionResponse(cache as never)).text()).toBe(raw);expect(cache.rows.get(2)?.payload).toMatch(/^gzip-json-v1:/);expect(await readProjectionRaw(cache as never)).toBe(raw);expect(fetcher).toHaveBeenCalledOnce();expect(await readProjection(cache as never)).toEqual(board);});
it('keeps raw last-good data on failure and retries the next read',async()=>{const fetcher=vi.fn().mockRejectedValue(Error('offline'));vi.stubGlobal('fetch',fetcher);const cache=db(0);expect(await readProjectionRaw(cache as never)).toBe(raw);expect(await readProjectionRaw(cache as never)).toBe(raw);expect(fetcher).toHaveBeenCalledTimes(2);expect(cache.run).not.toHaveBeenCalled();});
it('does not label legacy cache as original bytes; retains legacy UI fallback',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(Error('offline')));const cache=db(Date.now(),true);expect((await projectionResponse(cache as never)).status).toBe(503);expect(await readProjection(cache as never)).toEqual(board);expect(cache.rows.has(2)).toBe(false);});
it('migrates legacy cache without altering it and refreshes only raw row',async()=>{vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>served()));const cache=db(Date.now(),true);const before=cache.rows.get(1);expect(await readProjectionRaw(cache as never)).toBe(raw);await refreshProjection(cache as never);expect(cache.rows.get(1)).toEqual(before);expect(cache.rows.get(2)?.payload).toMatch(/^gzip-json-v1:/);});
it('failed cache write still serves exact valid source',async()=>{vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>served()));expect(await readProjectionRaw(db(0,true,true) as never)).toBe(raw);});
it('refuses redirect and malformed source, preserving raw last-good',async()=>{for(const response of [served('redirect',302),served('invalid')]){const fetcher=vi.fn().mockResolvedValue(response);vi.stubGlobal('fetch',fetcher);const cache=db(0);expect(await readProjectionRaw(cache as never)).toBe(raw);expect(cache.run).not.toHaveBeenCalled();expect(fetcher.mock.calls[0][1].redirect).toBe('manual');}});
it('cannot regress publication or overwrite frozen records',async()=>{const cache=db(0);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(served(raw.replace('20:00','19:00'))));expect(await readProjectionRaw(cache as never)).toBe(raw);expect(cache.run).not.toHaveBeenCalled();});
it('warm raw cache needs no source request',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);expect(await readProjectionRaw(db(Date.now()) as never)).toBe(raw);expect(fetcher).not.toHaveBeenCalled();});
it('rejects corrupted compressed cache rather than serving a false success',async()=>{vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>served()));const cache=db(0);await readProjectionRaw(cache as never);const saved=cache.rows.get(2)!;saved.payload=saved.payload.replace(/"sha256":"[a-f0-9]+"/,'"sha256":"bad"');vi.stubGlobal('fetch',vi.fn().mockRejectedValue(Error('offline')));expect((await projectionResponse(cache as never)).status).toBe(503);});
it('rejects a changed frozen game and preserves earlier raw data',async()=>{const frozen={...board,games:[{game_id:'locked',status:'FINAL',projection:{home_points:20,away_points:20,margin:0,total:40,home_win_probability:.5},display:{home_points:20,away_points:20,margin:0,total:40,home_win_probability:.5},version:'v1',why:{against:'Against: fixture'},evidence:'RETROSPECTIVE'}]};const cache=db(0);cache.rows.set(2,{payload:JSON.stringify(frozen),checked_at:0});const changed={...frozen,games:[{...frozen.games[0],version:'v2'}]};vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>served(JSON.stringify(changed))));expect(await readProjectionRaw(cache as never)).toBe(JSON.stringify(frozen));expect(cache.run).not.toHaveBeenCalled();});
it('an older in-flight download cannot replace a later cache commit',async()=>{let clock=1000;vi.spyOn(Date,'now').mockImplementation(()=>clock);const cache=db(0);let finish:(value:Response)=>void=()=>{};const newer=raw.replace('20:00','21:00');const fetcher=vi.fn().mockImplementationOnce(()=>new Promise<Response>(resolve=>{finish=resolve;})).mockImplementation(async()=>served(newer));vi.stubGlobal('fetch',fetcher);const old=readProjectionRaw(cache as never,true);await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledOnce());clock=2000;expect(await readProjectionRaw(cache as never,true)).toBe(newer);clock=3000;finish(served());await old;expect(cache.rows.get(2)?.checked_at).toBe(2000);expect(await readProjectionRaw(cache as never)).toBe(newer);});
