import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {suit,visibleEntries} from '../src/server/suit';
import {priceEntry,eligible,validateEntry,type Board,type Game,type Entry} from '../src/domain/suit';
const entry={game_id:'G',person:'Gabe',spread:-5,total:48,confidence:1,tags:['PRICE'],submitted_at:'2026-09-12T00:00:00Z',input_class:'PRE_OPEN',confidence_map:{'1':.52,'2':.55,'3':.58,'4':.62,'5':.66},confidence_version:'v1'} as Entry;
const game={game:{game_id:'G',home_team:'B',away_team:'A',cutoff_at:'2099-01-01T00:00:00Z'},early_at:'2098-01-01T00:00:00Z',context:{consensus:{spreads:{full:{center:3}},totals:{full:{center:45}}},offers:[{market:'spreads',side:'B',line:-3,price:-110,book:'betmgm'}]}} as unknown as Game;
const board={confidence_config:{version:'v1',people:{Gabe:{provisional:entry.confidence_map},Jarrett:{provisional:entry.confidence_map}}},schema:'iron-man-suit-v1',as_of:'2026-09-12T00:00:00Z',games:[game],feedback:{rows:[],calibration:[]},confidence_maps:null,distribution:{targets:{margin:{counts:{'-3':1,'0':2,'3':1}},total:{counts:{'-3':1,'0':2,'3':1}}}}} as unknown as Board;
function database(b:Board=board){const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE engine_suit_entries(game_id TEXT, person TEXT, payload TEXT, cutoff_at INTEGER, PRIMARY KEY(game_id,person)); CREATE TABLE engine_suit_publication(id INTEGER PRIMARY KEY,payload TEXT,checked_at INTEGER)');sql.prepare('INSERT INTO engine_suit_publication VALUES(1,?,?)').run(JSON.stringify(b),Date.now());
const db={prepare:(q:string)=>{let args:(string|number)[]=[];return {bind(...v:(string|number)[]){args=v;return this;},async first(){return sql.prepare(q).get(...args)||null;},async all(){return {results:sql.prepare(q).all(...args)};},async run(){return {meta:{changes:Number(sql.prepare(q).run(...args).changes)}};}}}} as unknown as D1Database;return {sql,db};}
const request=(key:string,method='GET',body?:unknown)=>new Request('https://example.com/api/suit-entry?gameId=G',{method,headers:{authorization:'Bearer '+key,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
describe('human suit privacy, pricing and confidence',()=>{
 it('does not expose partner before both submit',()=>{expect(visibleEntries([entry],'Jarrett')).toEqual([]);expect(visibleEntries([entry,{...entry,person:'Jarrett'}],'Gabe')).toHaveLength(2);});
 it('matches integer PMF pricing and keeps confidence out of Kelly',()=>{const a=priceEntry(entry,game,board)[0],b=priceEntry({...entry,confidence:5},game,board)[0];expect(a.fair_probability).toBe(.75);expect(a.push).toBe(0);expect(a.EV).toBeCloseTo(.4318181818181818,12);expect(a.stake_dollars).toBe(b.stake_dollars);expect(a.conflict).toBeUndefined();});
 it('hides conflict at 49 and reveals at 50 only for eligible person',()=>{const b=structuredClone(board);b.feedback.rows=[{person:'Gabe',population:'REGULAR',tag:'ALL',week:'ALL',phase:'ALL',input_class:'ALL',confidence:'ALL',graded:49}] as Board['feedback']['rows'];expect(eligible(b,'Gabe')).toBe(false);b.feedback.rows[0].graded=50;expect(priceEntry(entry,game,b)[0].conflict).toBe(true);expect(eligible(b,'Jarrett')).toBe(false);});
 it('rejects malformed confidence and non-finite numbers',()=>{expect(validateEntry(entry)).toBe(true);expect(validateEntry({...entry,spread:NaN})).toBe(false);expect(validateEntry({...entry,confidence:1.5})).toBe(false);});
 it('requires separate person credentials and protects sync',async()=>{const {db,sql}=database();const env={DB:db,GABE_EDIT_KEY:'gabe',JARRETT_EDIT_KEY:'jarrett',NOTE_SYNC_KEY:'sync'};expect((await suit(request('wrong'),env)).status).toBe(401);expect((await suit(new Request('https://example.com/api/suit-entry/sync'),env)).status).toBe(401);sql.close();});
 it('stores first entry atomically, hides partner, and rejects revision after reveal',async()=>{const {db,sql}=database(),env={DB:db,GABE_EDIT_KEY:'gabe',JARRETT_EDIT_KEY:'jarrett'};expect((await suit(request('gabe','POST',entry),env)).status).toBe(200);let r=await (await suit(request('jarrett'),env)).json() as {entries:Entry[]};expect(r.entries).toEqual([]);expect((await suit(request('jarrett','POST',{...entry,spread:2}),env)).status).toBe(200);r=await (await suit(request('gabe'),env)).json() as {entries:Entry[]};expect(r.entries).toHaveLength(2);expect(JSON.stringify(r)).not.toContain('confidence_map');expect((await suit(request('gabe','POST',{...entry,spread:4}),env)).status).toBe(409);sql.close();});
 it('rejects entry at expired cutoff and SQLite enforces cutoff independently',async()=>{const b=structuredClone(board);b.games[0].game.cutoff_at='2000-01-01T00:00:00Z';const {db,sql}=database(b);expect((await suit(request('gabe','POST',entry),{DB:db,GABE_EDIT_KEY:'gabe'})).status).toBe(409);const x=sql.prepare("INSERT INTO engine_suit_entries SELECT 'X','Gabe','{}',0 WHERE CAST(strftime('%s','now') AS INTEGER)*1000 < 0").run();expect(Number(x.changes)).toBe(0);sql.close();});
});
