# RF-COMP-02 bounded design review

Decision: suitable for a narrowly qualified candidate, not yet accepted as equivalent or faster. No numerical calls or tests were run for this review.

Installed-source inspection: SciPy 1.13.1 `scipy/stats/_distn_infrastructure.py`, `rv_discrete.cdf` lines 3470 onward, and `_discrete_distns.py`, `skellam_gen._cdf` lines 1572 onward. The public wrapper validates positive shape arguments and finite supported k, calls `argsreduce` (which converts accepted scalar arguments into length-one arrays), evaluates `_cdf`, applies `np.clip(..., 0, 1)`, writes to a float64 output array, and returns its scalar element. The private method floors x, enters `np.errstate(over='ignore')`, and uses `np.where` over two Boost noncentral-chi-square CDF expressions. Both expressions are evaluated, including the unselected branch. This is not a direct single-tail implementation.

Required narrow implementation conventions:

- Guard exact `type(k) is int`, excluding bool, subclasses and NumPy integers; inclusive `-2**20 <= k <= 2**20`. Guard exact float or np.float64 rate types, finite and strictly positive through 1e4. Everything else must call the unchanged public CDF with the original arguments. Do not cast before deciding eligibility, add loc/array semantics, or catch errors and retry through the public wrapper.
- Inside the guard, convert all three arguments to np.float64 before the private call, then apply exactly `np.clip(result, 0, 1)` and return np.float64. Do not substitute Python min/max, which changes NaN behavior. Preserve NaN, infinities and exceptions as the original operation produces them; do not add numerical repair. Clipping does not make a NaN finite.
- Keep the private `_cdf` intact. In particular, do not suppress `scipy.special` warnings/errors, add a broad NumPy errstate, or replace eager np.where with a Python branch. The current method suppresses only NumPy overflow. Its unselected Boost branch can receive nonpositive degrees of freedom; matching warnings/exceptions under nondefault special.errstate is part of equivalence, not an incidental detail.
- Scalar np.float64 versus length-one array execution is the remaining real semantic seam. Source inspection supports matching formulas but does not prove identical ufunc loop behavior, warning multiplicity or floating-point bits. Pin the installed SciPy implementation/runtime; this private API cannot be assumed stable across upgrades.

Minimum qualification should cover k=-1,0,1 and both guard endpoints; equal/asymmetric rates; smallest positive subnormal and very small normal rates as well as 1e4; values immediately outside each guard; booleans, NumPy integers, float k, arrays, float32, invalid rates and subclasses on fallback. Compare exact scalar type and IEEE bytes, including signed zero, and captured warnings/exception class under default and selected NumPy/scipy.special error modes. These are test design recommendations only. The allowed positive domain has no lower numerical floor, so tiny positive rates cannot be omitted from qualification merely because football rates are larger.

Retain the accepted Poisson helper and empirical accumulation order unchanged. Full scorer/JSON equivalence and a paired full-cost measurement remain necessary before any speed or scientific-reuse claim. An observed profile fraction is motivation, not an achievable overall speedup estimate. No historical restart or RF-02F alteration follows from this review.

Superseding interface refinement agreed with root: retain public `argsreduce` backend shapes rather than the initially proposed scalar call. Use `np.array([k], dtype=np.int64)`, `np.array([r], dtype=np.float64)` and `np.array([s], dtype=np.float64)`, followed by `np.clip(skellam._cdf(...), 0, 1)[0]`. Default loc subtraction preserves the eligible integer k before `_cdf` floors it. The bounded k fits int64 exactly. This removes the identified scalar-versus-length-one ufunc seam and is the recommended candidate interface. Explicit shape/dtype spies and error-mode comparisons should confirm this correspondence; numerical acceptance is still pending.
