# RF-COMP-03: exact per-fit encoding reuse

The preceding goal turn made progress: RF-COMP-02 was implemented, qualified with 18 focused tests and 168 exact saved observations, and independently accepted for exactness but a strict timing miss. It did not establish historical capacity. The measured remaining fit cost includes three encodings of alpha; test this one dependency next instead of rerunning a benchmark to seek favorable timing.

Hypothesis: encode a complete, identical finite-float list once within a fit, reusing the original bytes on exact subsequent matches while preserving all independent reconstruction and authentication. Every key must use every IEEE754 bit from a freshly captured immutable tuple, including signed zero and length. One successful entry only; unsupported inputs retain their original argument to the original encoder and do not clear the entry. A failed encoding must leave the previous entry intact. Bind the original serializer once per memo instance. This is ordinary synchronous use, not a new concurrent-mutation or exhausted-memory guarantee.

The candidate is a new separately pinned module. EncodingMemo is allocated inside the actual timed callback and has no lifetime beyond that callback. Use explicit encode parameters on source-equivalent copies of descriptor creation and independent recovery. The archive schema/class check and its AdmissionFailure type must be preserved, distinct from forecast ValueError checks. EncodingAssembly changes only resolve; original source/fallback recovery, strict JSON, fresh mapper.components, alpha SHA, beta/rates, recovered moments, frozen law copies and complete descriptor roundtrip all remain. No global encoder rebinding, dynamic function cloning, cross-fit cache, scientific math change, or historical entry point.

Before execution, statically compare the copies against frozen source ASTs, review isolation and actual call sites, read the focused tests, and pin candidate/test/driver/scope/reviews, accepted RF-COMP-01/02 evidence and references, original66files, and the pinned Python/NumPy/SciPy serializer/backend dependencies. Preserve every earlier attempt and accepted file unchanged. One new owned command is authorized, including imports, authentication, tiny synthetic setup, focused tests, callback timing, comparisons and persistence, under 60 seconds and 1,024 MiB with an external observer. Stop at the first unexpected failure or mismatch and retain the command/log/process result/completed bodies. No automatic retry.

Focused tests must show exact original JSON bytes for signed zeros, empty and changed-length lists, finite extremes/subnormals and repeated fresh lists. Check caller mutation, one-entry eviction, no cross-fit reuse, unchanged unsupported input identity, nonfinite/subclass fallback, captured encoder configuration and commit only after success. Compare actual descriptors and reconstructed law fields. Inject changed recovered alpha (first/last element, length, signed zero), saved alpha hash, beta/rates/mean/covariance and schema/class errors. Every original failure class/message and components/hash/moment/full-roundtrip check must still run on cache hits. Include real Assembly normal/fallback/error behavior, allocation inside callback, no shared global changes and independent memo instances. Reuse prior probability suites instead of rerunning unchanged helpers; full score equality is still checked at the new integration boundary.

Benchmark the same eight accepted synthetic cases: control3/synthetic700 supports, setting10 full and independent_marginals, setting6 zero_strength_update and zero_scoring_level_update, genuine tiny Elo bank/means, z-target, observed[21,17]. Three modes: original fit and original scorer; original fit and accepted Skellam scorer; new memoized fit and accepted Skellam scorer. The original descriptor/recovery/encoder path remains available as oracle. Both scoring flags are true in every mode. The partial synthetic Assembly setup is explicit; historical admission/constructor and full chronological controller are outside this scope.

One warmup per mode and six measured rounds per case, rotating three modes so each appears in each position twice: exactly168fit and168scorecallbacks, including warmups but excluding focused tests and fixture creation. Include memo allocation, snapshot/key work, all verification and callback computation inside fit timing. Persist each completed descriptor, full104field metric body and canonical recovered-law hash before checking against the pinned accepted original reference. Record raw timing and source maps before/after; all original66files and prior candidates remain exact.

Compare unprofiled separate maxima from measured rounds: synthetic700 full fitting plus the two setting6 controls' scoring, and broader full-fit/all-score stress. Report original, accepted Skellam and composed memo modes, plus the unchanged historical F+S target0.007461491790146312seconds. Do not substitute rounded results, medians, selected timings or a new target. A synthetic threshold pass would be a limited lead only: historical baseline/resources differ, and the historical52.468percent requirement remains. Require distinct independent evidence review after the one command.

No RF-02F restart, historical fitting/scoring/inference/bootstrap, full-controller integration, source admission, new model/prospective/predictive claim or research publication is authorized by this experiment. The goal stays active with enhanced Elo, external5percent, prospective and useful-product requirements intact.
