"use client";
import {useState,type CSSProperties} from 'react';
import type {Card,Tile,Value} from '../domain/game-card-v3';
import type {LockedGame} from '../domain/locked-board';
import {TicketPick,GameTicketPicker} from './ticket-slip';
const TAGS=['QB matchup','coordinator','trenches','injury','scheme','situation','weather','young QB support','pressure vs explosives','momentum','continuity','officiating'];
export const odds=(v:number|null|undefined)=>v==null?'N/R':`${v>0?'+':''}${v}`;
const when=(v:string|null)=>v?new Date(v).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' PT':'not recorded';
const logo=(v:string)=>`/team-logos/${({LA:'lar',WAS:'wsh'} as Record<string,string>)[v]??v.toLowerCase()}.png`;
const result=(v:string)=>({W:'WIN',L:'LOSS',P:'PUSH',PUSH:'PUSH'} as Record<string,string>)[v]??v;
function Values({value}:{value:Value}){if(value===null)return <span className="gc-muted">N/R</span>;if(Array.isArray(value))return <span>{value.map(v=>typeof v==='object'?JSON.stringify(v):String(v)).join(', ')}</span>;if(typeof value!=='object')return <span>{typeof value==='number'?Number.isInteger(value)?value:value.toFixed(3):String(value)}</span>;return <dl className="gc-values">{Object.entries(value).map(([key,v])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd><Values value={v}/></dd></div>)}</dl>;}
function NumberEntry({card}:{card:Card}){
 const [code,setCode]=useState(''),[spread,setSpread]=useState(''),[total,setTotal]=useState(''),[confidence,setConfidence]=useState('3'),[tags,setTags]=useState<string[]>([]),[text,setText]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(){setBusy(true);try{const r=await fetch(`/api/card-entry?gameId=${encodeURIComponent(card.game_id)}`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${code}`},body:JSON.stringify({spread:Number(spread),total:Number(total),confidence:Number(confidence),tags,text})});const data=await r.json() as {error?:string;message:string};if(!r.ok)throw Error(data.error);setMessage(data.message);setCode('');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 return <form className="gc-entry" onSubmit={e=>{e.preventDefault();void submit();}}><h3>Our number</h3><p>Our shared lean. A late entry is saved as POST_LOCK and cannot change a frozen pick.</p><label>Team edit code<input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} required/></label><div className="gc-entry-pair"><label>{card.home} fair spread<input type="number" step="0.5" min="-60" max="60" value={spread} onChange={e=>setSpread(e.target.value)} required/></label><label>Fair total<input type="number" step="0.5" min="0" max="150" value={total} onChange={e=>setTotal(e.target.value)} required/></label></div><label>Confidence<select value={confidence} onChange={e=>setConfidence(e.target.value)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><fieldset><legend>Reason tags</legend>{TAGS.map(t=><label key={t}><input type="checkbox" checked={tags.includes(t)} onChange={()=>setTags(tags.includes(t)?tags.filter(x=>x!==t):[...tags,t])}/>{t.replaceAll('_',' ').toLowerCase()}</label>)}</fieldset><label>Our football reason<textarea rows={2} maxLength={95} value={text} onChange={e=>setText(e.target.value)}/></label><button className="gc-action" disabled={busy||!tags.length}>{busy?'Saving…':'Save our number'}</button>{message&&<p role="status">{message}</p>}{card.ours&&<Values value={card.ours}/>}</form>;
}
function VerdictTile({tile:t,game}:{tile:Tile;game?:LockedGame}){
 const content=<b className="gc-pick">{t.pick}</b>;
 return <section className="gc-tile" tabIndex={0} aria-label={`${t.label}: ${t.pick??'NOT_RECORDED'}${t.probability_percent!=null?`, probability ${t.probability_percent} percent`:''}`}><h3>{t.label}</h3>{!t.pick?<span className="gc-nr">NOT_<wbr/>RECORDED</span>:<>
 {content}
 <div className="gc-ring" role="img" aria-label={t.probability_percent==null?'Probability not recorded':`${t.probability_percent}% probability`} style={{'--ring-offset':t.ring_offset} as CSSProperties}><svg viewBox="0 0 44 44" aria-hidden="true"><circle className="gc-ring-track" cx="22" cy="22" r="19"/><circle className="gc-ring-fill" cx="22" cy="22" r="19" pathLength="100"/></svg><span>{t.probability_percent??'N/R'}{t.probability_percent!=null?'%':''}</span></div><small className="gc-source">{t.confidence_source??'N/R'}</small>{t.subtitle&&<small>{t.subtitle}</small>}{t.chip&&<small>{t.chip}</small>}{t.grade&&t.grade!=='NOT_RECORDED'&&<strong className={`gc-grade gc-${t.grade.toLowerCase()}`}>{t.grade}</strong>}{t.clv!=null&&<small>CLV {t.clv.toFixed(1)}¢</small>}</>}
 </section>;
}
export function GameCard({card:c,game,initialExpanded=false}:{card:Card;game?:LockedGame;initialExpanded?:boolean}){
 const [open,setOpen]=useState(initialExpanded);const bar=c.winner_bar;
 return <article className="gc-card" data-game={c.game_id} aria-label={`${c.away} at ${c.home}`}><header className="gc-card-header"><div className="gc-match"><img src={logo(c.away)} width="32" height="32" alt={`${c.away} logo`} style={{borderColor:c.team_colors[c.away]}}/><b>{c.away}</b><span>at</span><img src={logo(c.home)} width="32" height="32" alt={`${c.home} logo`} style={{borderColor:c.team_colors[c.home]}}/><b>{c.home}</b></div><div className="gc-status"><span className="gc-badge">{c.status}</span><small>{c.status==='FINAL'&&c.final?`${c.away} ${c.final.away_score}–${c.home} ${c.final.home_score}`:c.status==='MISSED'?'no lock':when(c.status==='LOCKED'?c.freeze_timestamp:c.kickoff_utc)}</small>{c.status==='UPCOMING'&&c.stale&&<span className="gc-badge">STALE</span>}</div></header>
 <div className="gc-winner-bar" aria-label="Outright winner probabilities"><div style={{width:`${bar.away_width}%`,background:c.team_colors[c.away]}}><span className={c.tiles.WINNER.side===c.away?'favored':''}>{bar.away_percent!=null?`${bar.away_percent}%`:'N/R'}</span></div><div style={{width:`${bar.home_width}%`,background:c.team_colors[c.home]}}><span className={c.tiles.WINNER.side===c.home?'favored':''}>{bar.home_percent!=null?`${bar.home_percent}%`:'N/R'}</span></div></div>
 <div className="gc-tiles">{(['WINNER','SPREAD','TOTAL'] as const).map(k=><VerdictTile key={k} tile={c.tiles[k]} game={game}/>)}</div>
 <p className="gc-consensus">Line: {c.home} {odds(c.market.spread)} · Total {c.market.total??"N/R"}</p>
 {Object.values(c.sheet).some(b=>b.measured)&&(c.why.statement||c.why.bullets.length>0)&&<section className="gc-why" aria-label="Why we lean this way"><p className="gc-lean">{c.why.statement}</p><ul>{c.why.bullets.map(line=><li key={line}>{line}</li>)}</ul></section>}
 {c.wagers.map((p,i)=><p className="gc-wager" key={i}>Our wager · {p.side===game?.home_team?c.home:p.side===game?.away_team?c.away:p.side} {odds(Number(p.line_at_approval))} · <b className={`gc-result-${result(p.outcome).toLowerCase()}`}>{result(p.outcome)}</b></p>)}
 <footer className="gc-footer"><span title={c.version}>{c.version.replace(/([a-f0-9]{8})[a-f0-9]+/g,'$1')}<br/>Freeze {when(c.freeze_timestamp)}</span><button aria-expanded={open} aria-controls={`gc-detail-${c.game_id}`} onClick={()=>setOpen(!open)}>{open?'Collapse ↑':'Expand ↓'}</button></footer>
 {open&&<div className="gc-expanded" id={`gc-detail-${c.game_id}`}>{['4','6','7','9','10'].map(n=>{const b=c.sheet[n];return <section key={n}><h3>{n} · {b?.name??'Not recorded'}</h3>{b?<><small>{b.data_window}</small>{Object.entries(b.teams).map(([team,v])=><details key={team}><summary>{team} · values, ranks &amp; samples</summary><Values value={v}/></details>)}</>:<p>N/R</p>}</section>;})}<NumberEntry card={c}/><section><h3>Analysis</h3><p>Captured {when(c.market.capture_time)}.</p></section></div>}
 </article>;
}
