"use client";
import {useEffect,useState} from 'react';
import type {LockedGame} from '../domain/locked-board';
export function OurNote({game}:{game:LockedGame}){
  const [code,setCode]=useState('');const [author,setAuthor]=useState<'Gabe'|'Jarrett'>('Gabe');
  const [text,setText]=useState(game.our_note?.text??'');const [market,setMarket]=useState<'spreads'|'totals'|''>(game.our_note?.market??'');const [side,setSide]=useState(game.our_note?.side??'');
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [clock,setClock]=useState(()=>Date.now());
  const deadline=Date.parse(game.note_deadline??game.cutoff_at??'')||Date.parse(game.kickoff_at)-75*60_000;
  const locked=game.lock_status==='LOCKED'||game.lock_status==='MISSED'||game.status==='FINAL'||clock>=deadline;
  useEffect(()=>{const tick=setInterval(()=>setClock(Date.now()),1000);const load=setTimeout(()=>setCode(sessionStorage.getItem('nfl-team-edit-code')??''),0);return()=>{clearInterval(tick);clearTimeout(load);};},[]);
  const load=async()=>{setBusy(true);try{const r=await fetch(`/api/our-note?game_id=${encodeURIComponent(game.game_id)}`,{headers:{authorization:`Bearer ${code}`},cache:'no-store'});const d=await r.json() as {error?:string;note?:NonNullable<LockedGame["our_note"]>};if(!r.ok)throw new Error(d.error);sessionStorage.setItem('nfl-team-edit-code',code);if(d.note){setText(d.note.text);setMarket(d.note.market);setSide(d.note.side);setAuthor(d.note.author);}setMessage(d.note?'Saved note loaded.':'No saved note yet.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to load note.');}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);try{const r=await fetch(`/api/our-note?game_id=${encodeURIComponent(game.game_id)}`,{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${code}`},body:JSON.stringify({author,text,market,side})});const d=await r.json() as {error?:string;note?:NonNullable<LockedGame["our_note"]>};if(!r.ok)throw new Error(d.error);sessionStorage.setItem('nfl-team-edit-code',code);setMessage('Saved. This note and lean will freeze at T-75.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed; your draft is still here.');}finally{setBusy(false);}};
  return <section className="our-note"><h3>OUR NOTE</h3>{locked?<><p>{game.our_note?.text||'No note was saved before the lock.'}</p>{game.our_note?.side&&<p>{game.our_note.author} · {game.our_note.side} · {game.our_note.market} {game.human_lean_grade?`· ${game.human_lean_grade==='W'?'WIN':game.human_lean_grade==='L'?'LOSS':'PUSH'}`:''}</p>}<small>Locked — edits are closed.</small></>:<>
    <div className="note-controls"><label>Team edit code <input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={!code||busy} onClick={()=>void load()}>Load saved note</button><label>By <select value={author} onChange={e=>setAuthor(e.target.value as 'Gabe'|'Jarrett')}><option>Gabe</option><option>Jarrett</option></select></label></div>
    <label className="note-text-label">Our note<textarea value={text} maxLength={2000} rows={3} onChange={e=>setText(e.target.value)} placeholder="What are we seeing?"/></label>
    <div className="note-controls"><label>Lean <select value={market} onChange={e=>{setMarket(e.target.value as typeof market);setSide('');}}><option value="">No lean</option><option value="spreads">Spread</option><option value="totals">Total</option></select></label>{market&&<label>Side <select value={side} onChange={e=>setSide(e.target.value)}><option value="">Choose side</option>{(market==='spreads'?[game.away_team,game.home_team]:['Over','Under']).map(s=><option key={s}>{s}</option>)}</select></label>}<button disabled={!code||busy||!!market&&!side} onClick={()=>void save()}>{busy?'Saving…':'Save note & lean'}</button></div><small>Shared by Gabe and Jarrett. Closes at T-75; the locked lean is scored separately as human_lean.</small></>}{message&&<p role="status">{message}</p>}</section>;
}
