"use client";
import {useState} from 'react';
import type {ProjectionCardData,Scorecard} from '../domain/projection';
import {Trajectory} from './projection-trend';
import {integer,integerText,pointShare} from './board-v4-format';
const pct=(n:number)=>integer(n*100)+'%';
const localTime=(s:string)=>new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export function AccuracyRows({rows}:{rows:Scorecard[]}){const visible=rows.filter(r=>r.n>0);return <div className="b4-records">{visible.length?visible.map(r=><p key={[r.version,r.source,r.evidence].join(':')}><b>{r.source} · {r.evidence==='RETROSPECTIVE'?'retrospective':'as issued'}</b><span>{integer(r.n)} games · MAE {integer(r.metrics?.team_points.mae)} / {integer(r.metrics?.margin.mae)} / {integer(r.metrics?.total.mae)}</span></p>):<p>No graded projections</p>}</div>;}
function Entry({g}:{g:ProjectionCardData}){const [away,setAway]=useState(integer(g.ours?.away_points??g.projection?.away_points));const [home,setHome]=useState(integer(g.ours?.home_points??g.projection?.home_points));const [awayEdited,setAwayEdited]=useState(false);const [homeEdited,setHomeEdited]=useState(false);const [confidence,setConfidence]=useState(g.entry?.confidence??3);const [tags,setTags]=useState(g.entry?.tags.join(', ')??'');const [key,setKey]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/projection-entry?gameId='+encodeURIComponent(g.game_id),{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+key},body:JSON.stringify({projection_version:g.version,projection_issued_at:g.issued_at,away_points:awayEdited?Number(away):(g.ours?.away_points??g.projection?.away_points),home_points:homeEdited?Number(home):(g.ours?.home_points??g.projection?.home_points),confidence,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)})});const b=await r.json() as {error?:string};setMessage(r.ok?'Saved. The engine will update our projection shortly. Changes after the deadline remain post-lock.':integerText(b.error??'Unable to save. Your numbers remain here.'));}catch{setMessage('Unable to save. Your numbers remain here.');}finally{setBusy(false);}}
 return <form className="gc-entry" onSubmit={submit}><h3>Our projected score</h3><div className="gc-entry-pair"><label>{g.away}<input required type="number" min="0" max="100" step="1" value={away} onChange={e=>{setAwayEdited(true);setAway(e.target.value===''?'':integer(Number(e.target.value)));}}/></label><label>{g.home}<input required type="number" min="0" max="100" step="1" value={home} onChange={e=>{setHomeEdited(true);setHome(e.target.value===''?'':integer(Number(e.target.value)));}}/></label></div><label>Confidence<select value={confidence} onChange={e=>setConfidence(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Football reasons, separated by commas<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Run game, pass defense"/></label><label>Team edit code<input required type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="gc-action" disabled={busy}>{busy?'Saving…':'Save our score'}</button><p role="status">{message}</p></form>;
}

export function PointsBar({g}:{g:ProjectionCardData}){const prediction=g.ours??g.projection;const actual=g.final;if(!prediction||!g.projection)return <span className="b4-missing">Not recorded</span>;const p=actual??prediction;const share=pointShare(p.away_points,p.home_points),ghost=pointShare(prediction.away_points,prediction.home_points);return <div className={actual?'b4-points b4-overlay':'b4-points'}><span className="b4-score-line"><span>{g.ours?'Our pick':'Prediction'} <b>{g.away} {integer(prediction.away_points)} – {g.home} {integer(prediction.home_points)}</b></span><span>Total {integer(prediction.away_points+prediction.home_points)}</span></span><div className="b4-bar" aria-label={`${actual?'Final':'Prediction'}: ${g.away} ${integer(p.away_points)}, ${g.home} ${integer(p.home_points)}`}><div className="b4-segment b4-away" style={{width:`${share*100}%`,background:g.team_colors?.[g.away]??'#384352'}}><b>{g.away} {integer(p.away_points)}</b></div><div className="b4-segment b4-home" style={{width:`${(1-share)*100}%`,background:g.team_colors?.[g.home]??'#384352'}}><b>{g.home} {integer(p.home_points)}</b></div>{actual&&<span className="b4-ghost" aria-label="Predicted split" style={{width:`${ghost*100}%`}}/>}</div>{actual&&<span className="b4-score-line b4-final-label"><span>Final <b>{g.away} {integer(actual.away_points)} – {g.home} {integer(actual.home_points)}</b></span><span>Total {integer(actual.away_points+actual.home_points)}</span></span>}</div>;}
function Values({value}:{value:unknown}){if(value==null)return <span>Unavailable</span>;if(typeof value==='number')return <span>{integer(value)}</span>;if(typeof value==='string')return <span>{integerText(value)}</span>;if(typeof value==='boolean')return <span>{value?'Yes':'No'}</span>;if(Array.isArray(value))return <div>{value.map((v,i)=><Values key={i} value={v}/>)}</div>;return <dl className="b4-values">{Object.entries(value as Record<string,unknown>).filter(([k])=>!k.includes('hash')).map(([k,v])=><div key={k}><dt>{integerText(k.replaceAll('_',' '))}</dt><dd><Values value={v}/></dd></div>)}</dl>;}
export function ProjectionCard({g,expanded=false,onToggle=()=>{}}:{g:ProjectionCardData;expanded?:boolean;onToggle?:()=>void}){const p=g.display??g.projection;const original=g.projection;const margin=p?.margin??0;const marginText=margin===0?'Even':`${margin>0?g.home:g.away} by ${integer(Math.abs(margin))}`;const errors=g.grades?.[g.source]?.errors??g.grades?.PROJECTION?.errors;
 return <article className="b4-game" id={g.game_id} aria-label={`${g.away} at ${g.home}`}><button type="button" className={g.final?"b4-row b4-final-row":"b4-row"} aria-expanded={expanded} aria-controls={`analysis-${g.game_id}`} onClick={onToggle}><span className="b4-matchup"><span className="b4-teams"><img src={`/team-logos/${({LA:'lar',WAS:'wsh'} as Record<string,string>)[g.away]??g.away.toLowerCase()}.png`} alt=""/><b>{g.away}</b><span>at</span><img src={`/team-logos/${({LA:'lar',WAS:'wsh'} as Record<string,string>)[g.home]??g.home.toLowerCase()}.png`} alt=""/><b>{g.home}</b></span><small>{g.final?`FINAL ${integer(g.final.away_points)}–${integer(g.final.home_points)}`:localTime(g.kickoff_at)}</small></span><PointsBar g={g}/><span className="b4-result"><b>{original?marginText:'Not recorded'}</b>{g.final?<small>{g.final.home_points===g.final.away_points?'Game tied':(g.final.home_points>g.final.away_points?g.home:g.away)===g.winner?'Winner right':'Winner missed'}</small>:original&&<small>{pct(g.winner_probability)}</small>}</span></button>
 {expanded&&<div className="b4-analysis" id={`analysis-${g.game_id}`}>{original&&p?<><div className="b4-tiles"><section><h3>WINNER</h3><strong>{g.winner}</strong><span>{pct(g.winner_probability)}</span><small>Ties split evenly · {g.source}</small></section>{(['margin','total'] as const).map(k=><section key={k}><h3>{k.toUpperCase()}</h3><strong>{k==='margin'?marginText:integer(p.total)}</strong><span>50%: {p.intervals[k]['50'].map(integer).join(' to ')}</span><span>80%: {p.intervals[k]['80'].map(integer).join(' to ')}</span>{errors&&<small>Error {integer(errors[k])}</small>}</section>)}</div><section className="b4-why"><h3>Football WHY</h3><ul>{g.why.lines.map((s,i)=><li key={i}>{integerText(s)}</li>)}</ul><p>{integerText(g.why.against)}</p>{g.score_probability_note&&<p>{integerText(g.score_probability_note)}</p>}</section><Entry g={g}/><section><h3>Contributions</h3><div className="b4-contributions">{(['away','home'] as const).map(side=><div key={side}><h4>{g[side]}</h4><table><thead><tr><th>Input</th><th>Value</th><th>Points</th></tr></thead><tbody>{g.contributions[side].map(c=><tr key={c.input}><td>{integerText(c.label)}<small>{c.status}</small></td><td>{integer(c.value)}</td><td>{integer(c.points)}</td></tr>)}</tbody></table></div>)}</div></section><section><h3>Six-week trajectory</h3>{g.trajectory?(['away','home'] as const).map(side=><Trajectory key={side} team={g[side]} rows={g.trajectory![side]} integers/>):<p>Trajectory unavailable.</p>}</section><section><h3>Football sheet</h3>{['4','6','7','9','10'].map(n=>{const b=g.sheet?.[n];return <section className="b4-sheet" key={n}><h4>{n} · {b?.name??'Not recorded'}</h4>{b?<><small>{integerText(b.data_window)}</small>{Object.entries(b.teams).map(([team,value])=><details key={team}><summary>{team} · values and samples</summary><Values value={value}/></details>)}</>:<p>Unavailable</p>}</section>;})}</section></>:<p>{integerText(g.reason??'Projection unavailable.')}</p>}<footer>{integerText(g.version)} · {g.evidence==='RETROSPECTIVE'?'RETROSPECTIVE · ':''}{g.freeze_time?'Frozen '+localTime(g.freeze_time):'Updated '+localTime(g.issued_at)}</footer></div>}
 </article>;
}
