"use client";
import {useState,type CSSProperties} from 'react';
import type {ProjectionCardData,Scorecard} from '../domain/projection';
const num=(n:number)=>n.toFixed(1);const pct=(n:number)=>(n*100).toFixed(0)+'%';
function Ring({p}:{p:number}){return <div className="gc-ring" style={{'--ring-offset':100-p*100} as CSSProperties}><svg viewBox="0 0 44 44" aria-hidden="true"><circle className="gc-ring-track" cx="22" cy="22" r="18" pathLength="100"/><circle className="gc-ring-fill" cx="22" cy="22" r="18" pathLength="100"/></svg><span>{pct(p)}</span></div>;}
export function AccuracyRows({rows}:{rows:Scorecard[]}){return <div className="gc-records">{rows.map(r=><p key={(r.version??'')+r.source+r.evidence}><b>{r.source}{r.version?' · '+r.version.split('-').slice(0,2).join('-'):''} · {r.evidence==='RETROSPECTIVE'?'retrospective':'as issued'}</b><span>{r.n&&r.metrics?`${r.n} games · MAE ${num(r.metrics.team_points.mae)} / ${num(r.metrics.margin.mae)} / ${num(r.metrics.total.mae)}`:'No graded projections'}</span></p>)}<small>MAE: team points / margin / total</small></div>;}
function Entry({g}:{g:ProjectionCardData}){const [away,setAway]=useState(String(g.ours?.away_points??g.projection?.away_points.toFixed(1)));const [home,setHome]=useState(String(g.ours?.home_points??g.projection?.home_points.toFixed(1)));const [confidence,setConfidence]=useState(g.entry?.confidence??3);const [tags,setTags]=useState(g.entry?.tags.join(', ')??'');const [key,setKey]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/projection-entry?gameId='+encodeURIComponent(g.game_id),{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+key},body:JSON.stringify({away_points:Number(away),home_points:Number(home),confidence,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)})});const b=await r.json() as {error?:string};setMessage(r.ok?'Saved. The engine will update our projection shortly. Changes after the deadline remain post-lock.':b.error??'Unable to save. Your numbers remain here.');}catch{setMessage('Unable to save. Your numbers remain here.');}finally{setBusy(false);}}
 return <form className="gc-entry" onSubmit={submit}><h3>Our projected score</h3><div className="gc-entry-pair"><label>{g.away}<input required type="number" min="0" max="100" step="0.1" value={away} onChange={e=>setAway(e.target.value)}/></label><label>{g.home}<input required type="number" min="0" max="100" step="0.1" value={home} onChange={e=>setHome(e.target.value)}/></label></div><label>Confidence<select value={confidence} onChange={e=>setConfidence(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Football reasons, separated by commas<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Run game, pass defense"/></label><label>Team edit code<input required type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="gc-action" disabled={busy}>{busy?'Saving…':'Save our score'}</button><p role="status">{message}</p></form>;
}
export function ProjectionCard({g}:{g:ProjectionCardData}){const [expanded,setExpanded]=useState(false);const p=g.display;const original=g.projection;const time=new Date(g.kickoff_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});const accuracy=g.grades?.[g.source];
 return <article className="gc-card projection-card" id={g.game_id} aria-label={`${g.away} at ${g.home}`}><header className="gc-card-header"><div className="gc-match"><img src={`https://a.espncdn.com/i/teamlogos/nfl/500/${g.away==='LA'?'lar':g.away.toLowerCase()}.png`} alt="" style={{borderColor:g.team_colors?.[g.away]}}/><b>{g.away}</b><span>at</span><img src={`https://a.espncdn.com/i/teamlogos/nfl/500/${g.home==='LA'?'lar':g.home.toLowerCase()}.png`} alt="" style={{borderColor:g.team_colors?.[g.home]}}/><b>{g.home}</b></div><div className="gc-status"><span className="gc-badge">{g.status}{g.final?` ${g.away} ${g.final.away_points}–${g.home} ${g.final.home_points}`:''}</span><small>{time}</small>{g.evidence==='RETROSPECTIVE'&&<span className="gc-badge">RETROSPECTIVE</span>}</div></header>
 {!original?<p className="gc-nr">Not recorded · {g.reason}</p>:<><div className="gc-winner-bar" aria-label={`${g.away} ${pct(p.away_win_probability)}, ${g.home} ${pct(p.home_win_probability)}`}><div style={{width:pct(p.away_win_probability),background:g.team_colors[g.away]}}><span className={g.winner===g.away?'favored':''}>{pct(p.away_win_probability)}</span></div><div style={{width:pct(p.home_win_probability),background:g.team_colors[g.home]}}><span className={g.winner===g.home?'favored':''}>{pct(p.home_win_probability)}</span></div></div><p className="projection-score">Projected: {g.away} {num(original.away_points)} · {g.home} {num(original.home_points)}</p>{g.ours&&<p className="projection-score">Ours: {g.away} {num(g.ours.away_points)} · {g.home} {num(g.ours.home_points)}</p>}<div className="gc-tiles"><section className="gc-tile"><h3>Winner</h3><strong className="gc-pick">{g.winner}</strong><Ring p={g.winner_probability}/><small>{g.coin_flip?'Coin flip · ':''}{g.source}</small></section>{(['margin','total'] as const).map(k=><section className="gc-tile" key={k}><h3>{k}</h3><strong className="gc-pick">{k==='margin'?`${g.home} ${p.margin>=0?'+':''}`:''}{num(p[k])}</strong><small>likely {p.intervals[k]['80'].join(' to ')}</small><small>most likely {p.intervals[k]['50'].join(' to ')}</small><small>{g.source}</small>{accuracy&&<small>Actual {num(accuracy.actual[k])} · error {num(accuracy.errors[k])}<br/>50% {accuracy.interval_hits[k]['50']?'IN':'OUT'} · 80% {accuracy.interval_hits[k]['80']?'IN':'OUT'}</small>}</section>)}</div><div className="gc-why"><ul>{g.why.lines.map((line,i)=><li key={i}>{line}</li>)}<li>{g.why.against}</li></ul></div>{g.final&&<p className="gc-muted">Final {g.away} {g.final.away_points} · {g.home} {g.final.home_points}<br/>Team score error: {g.away} {num(accuracy!.errors.away_points)} · {g.home} {num(accuracy!.errors.home_points)}</p>}<footer className="gc-footer"><span>{g.freeze_time?'Frozen '+new Date(g.freeze_time).toLocaleString():'Updated '+new Date(g.issued_at).toLocaleString()}<br/>{g.version}</span><button aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>Analysis &amp; our score</button></footer>{expanded&&<div className="gc-expanded"><Entry g={g}/><p>Margin is {g.home} minus {g.away}. Intervals include 50% (“most likely”) and 80% (“likely”) of the fitted residual distribution. Positive error means actual points exceeded the projection.</p>{(['away','home'] as const).map(side=><details key={side}><summary>{g[side]} input contributions</summary><dl className="gc-values">{g.contributions[side].map(c=><div key={c.input}><dt>{c.label} · {c.status}</dt><dd>{num(c.points)} points · measured {c.value===null?'unavailable':c.value?.toFixed(3)}<small> · {c.source_hashes.map(h=>h.slice(0,8)).join(', ')}</small></dd></div>)}</dl></details>)}</div>}</>}
 </article>;
}
