"use client";
import {useEffect,useState} from 'react';
import type {ProjectionBoardData} from '../domain/projection';
import {ProjectionCard,AccuracyRows} from './projection-card';
import '../styles/game-card-v3.css';
import '../styles/projection.css';
export function ProjectionBoard(){const [board,setBoard]=useState<ProjectionBoardData|null>(null);const [week,setWeek]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function load(fresh=false){setBusy(true);try{const r=await fetch('/api/projection-board'+(fresh?'?refresh=1':''),{cache:'no-store'});if(!r.ok)throw Error('Projections are temporarily unavailable.');setBoard(await r.json());setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load projections');}finally{setBusy(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[]);
 return <main className="gc-root gc-board"><header className="gc-week"><label>Week <select value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=><option value={i+1} key={i+1}>{i+1}</option>)}</select></label><button disabled={busy} onClick={()=>void load(true)}>{busy?'Updating…':'Refresh projections'}</button>{board&&<AccuracyRows rows={board.scorecards.filter(r=>r.week===week)}/>}</header>{board&&<details className="gc-expanded"><summary>Accuracy by week and season</summary>{board.scorecards.filter(r=>r.week===week||r.week===null).map(r=><section key={r.source+r.evidence+String(r.week)}><h3>{r.source} · {r.evidence} · {r.week===null?'Season':`Week ${week}`} · {r.n} games</h3>{r.metrics?<table><thead><tr><th>Target</th><th>MAE</th><th>Sigma</th><th>50%</th><th>80%</th></tr></thead><tbody>{Object.entries(r.metrics).map(([target,m])=><tr key={target}><td>{target.replace('_',' ')}</td><td>{m.mae.toFixed(2)}</td><td>{m.sigma?.toFixed(2)??'—'}</td>{['50','80'].map(level=><td key={level}>{m.coverage?.[level]?`${(m.coverage[level].rate*100).toFixed(1)}%${m.coverage[level].flag?' *':''}`:'—'}</td>)}</tr>)}</tbody></table>:<p>No graded projections.</p>}</section>)}<small>* More than three percentage points from nominal coverage. Retrospective reconstructions remain separate from as-issued forecasts.</small></details>}{error&&<p role="status">{error}</p>}{!board&&!error&&<p>Loading football projections…</p>}<div className="gc-grid">{board?.games.filter(g=>g.week===week).map(g=><ProjectionCard g={g} key={g.game_id}/>)}</div></main>;
}
