"use client";
import {useEffect,useState} from "react";
import {type Board,type Game,type Team,TAGS} from "../domain/suit";
import "./suit-sheet.css";
const fmt=(v:unknown,d=2)=>typeof v==="number"?v.toFixed(d):"Unknown";
const pct=(v:unknown)=>typeof v==="number"?(100*v).toFixed(1)+"%":"—";
type Reply={person?:string;revealed?:boolean;error?:string;locked?:boolean;entries?:{person:string;spread:number;total:number;confidence:number;tags:string[];input_class:string;pricing:{market:string;status:string;gap?:number;side?:string;line?:number;book?:string;price?:number;fair_probability?:number;edge_cents?:number;stake_dollars?:number;conflict?:boolean}[]}[]};
function NumberEntry({g}:{g:Game}) {
 const [code,setCode]=useState(""),[spread,setSpread]=useState(""),[total,setTotal]=useState(""),[confidence,setConfidence]=useState(3),[tags,setTags]=useState<string[]>([]),[reply,setReply]=useState<Reply>({}),[busy,setBusy]=useState(false);
 async function send(post=false){setBusy(true);try{const r=await fetch("/api/suit-entry?gameId="+encodeURIComponent(g.game.game_id),{method:post?"POST":"GET",headers:{authorization:"Bearer "+code,"content-type":"application/json"},...(post?{body:JSON.stringify({spread:Number(spread),total:Number(total),confidence,tags})}:{})});setReply(await r.json());}catch{setReply({error:"Connection unavailable; entry not confirmed"});}finally{setBusy(false);}}
 const own=reply.entries?.some(e=>e.person===reply.person),closed=Date.now()>=Date.parse(g.game.cutoff_at);
 return <section className="suit-panel"><h2>Your number <small>Independent first. Price second.</small></h2><p>Home handicap: negative favors {g.game.home_abbr}. Under 1 point: STORY · 1–2: LEAN · over 2: BET, subject to price. Opposite sides: PASS unless one confidence is 4–5 and the other below 3. Same side uses the lower-confidence person's number.</p>
 <div className="suit-entry"><label>Personal edit code<input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy||!code} onClick={()=>send()}>Unlock my entry</button></div>
 {!own&&!closed&&<form onSubmit={e=>{e.preventDefault();send(true);}}><div className="suit-entry"><label>{g.game.home_abbr} handicap<input required type="number" min="-60" max="60" step="0.5" value={spread} onChange={e=>setSpread(e.target.value)}/></label><label>Game total<input required type="number" min="0" max="150" step="0.5" value={total} onChange={e=>setTotal(e.target.value)}/></label><label>Confidence<select value={confidence} onChange={e=>setConfidence(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="suit-tags">{TAGS.map(t=><label key={t}><input type="checkbox" checked={tags.includes(t)} onChange={()=>setTags(tags.includes(t)?tags.filter(v=>v!==t):[...tags,t])}/>{t.replaceAll("_"," ")}</label>)}</div><button disabled={busy||!code||!tags.length}>Submit independent numbers</button><small>First submission is final. Your partner's numbers stay hidden until both have submitted. Personal codes identify the author.</small></form>}
 {closed&&<p>LOCKED · Entry window closed.</p>}{reply.error&&<p role="alert">{reply.error}</p>}{reply.person&&<p>{reply.person} · {reply.revealed?"Both entries are in.":"Partner's entry hidden."}</p>}
 {reply.entries?.map(e=><div className="suit-lean" key={e.person}><b>{e.person}: {g.game.home_abbr} {e.spread>0?"+":""}{e.spread} · total {e.total} · confidence {e.confidence}</b><small>{e.input_class} · {e.tags.join(" · ")}</small>{e.pricing.map(p=><p key={p.market}>{p.market==="spreads"?"Spread":"Total"}: {p.status} {p.side&&<> · {p.side} {p.line} · {p.book} {p.price} · gap {fmt(p.gap)} · cover {pct(p.fair_probability)} · edge {fmt(p.edge_cents,1)}¢ · quarter Kelly ${fmt(p.stake_dollars)}</>}{p.conflict&&<strong> · CONFLICT</strong>}</p>)}</div>)}
 <small>Quote sizes are individual estimates; the lock applies the $100 combined game cap and $1,000 weekly budget. Confidence does not supply Kelly probability. EARLY: {new Date(g.early_at).toLocaleString()} · LATE: {new Date(g.game.cutoff_at).toLocaleString()}.</small></section>;
}
const efficiency=["points_per_drive","yards_per_play","epa","success"];
const matchup=["rush_epa","rush_success","pass_epa","pass_success","cpoe","pressure_rate","explosive_rate","epa_pressured"];
function Metrics({g,title,names}:{g:Game;title:string;names:string[]}){return <section className="suit-panel"><h2>{title}</h2><div className="suit-scroll"><table><thead><tr><th>Sensor</th><th>{g.game.away_abbr} · raw / adjusted / rank</th><th>{g.game.home_abbr} · raw / adjusted / rank</th></tr></thead><tbody>{names.flatMap(n=>["off","def"].map(side=><tr key={side+n}><th>{side==="off"?"Offense":"Defense"} · {n.replaceAll("_"," ")}</th>{[g.game.away_abbr,g.game.home_abbr].map(t=>{const v=g.teams[t].metrics[side+"_"+n];return <td key={t}>{v? <>{fmt(v.raw)} / {fmt(v.adjusted)} / {v.rank?"#"+v.rank:"—"}<small>{v.n_games} team-games</small></>:"Unknown"}</td>;})}</tr>))}</tbody></table></div><small>Descriptive ridge opponent adjustment; no automatic change to your number. Source hashes in the evidence drawer below.</small></section>;}
function Teams({g,title,render}:{g:Game;title:string;render:(t:Team)=>React.ReactNode}){return <section className="suit-panel"><h2>{title}</h2><div className="suit-two">{[g.game.away_abbr,g.game.home_abbr].map(t=><div key={t}><h3>{t}</h3>{render(g.teams[t])}</div>)}</div></section>;}
export function SuitSheet(){const [board,setBoard]=useState<Board|null>(null),[id,setId]=useState(""),[error,setError]=useState("");useEffect(()=>{fetch("/api/suit-board").then(async r=>{if(!r.ok)throw Error("Sheet unavailable; last-good board is retained.");return r.json() as Promise<Board>;}).then(b=>{setBoard(b);setId(b.games[0]?.game.game_id||"");}).catch(e=>setError(e.message));},[]);
 if(!board)return <div className="suit-sheet"><h1>Pre-game sheet</h1><p>{error||"Loading measured fields…"}</p><a href="/sunday">Back to board</a></div>;const g=board.games.find(g=>g.game.game_id===id)!;
 const rows=board.feedback.rows.filter(r=>r.week==="ALL"&&r.phase==="ALL"&&r.input_class==="ALL"&&r.confidence==="ALL"&&r.population==="REGULAR"&&(r.tag==="ALL"||r.graded>0));
 return <main className="suit-sheet"><header><div><small>BETA · HUMAN DECISIONS, MEASURED INPUTS</small><h1>Week {board.week} / Pre-game sheet</h1></div><a href="/sunday">Game board ↗</a></header><div className="suit-toolbar"><select aria-label="Game" value={id} onChange={e=>setId(e.target.value)}>{board.games.map(g=><option key={g.game.game_id} value={g.game.game_id}>{g.game.away_abbr} at {g.game.home_abbr}</option>)}</select><span className="suit-badge">{board.status}</span><time>{new Date(g.game.kickoff_at).toLocaleString()}</time></div><h2>{g.game.away_team} at {g.game.home_team}</h2><p className="suit-outside">{g.outside_view}</p><small>Situational base rate: MEASURE · no promoted study, no rate asserted. Source window: 2016–2025 REG.</small>
 <Metrics g={g} title="04 / Efficiency" names={efficiency}/><Metrics g={g} title="06 / Matchups" names={matchup}/>
 <Teams g={g} title="06 / QB support · own hypothesis" render={t=><><p>TE target share {pct(t.composition.te_target_share?.value)} · RB target share {pct(t.composition.rb_target_share?.value)}</p><p>Career REG starts: {t.qb.career_starts ?? "unknown"} · run-block snap share: unknown</p><small>{t.support.status}. Pressure vs explosive is diagnostic only; compare pressure generated with the opposing offense's explosive rate and EPA under pressure above.</small></>}/>
 <Teams g={g} title="07 / Quarterback" render={t=><><b>{t.qb.name||"Starter unknown"}</b><p>EPA/dropback {fmt(t.qb.epa_per_dropback)} · CPOE {fmt(t.qb.cpoe)} · NGS CPOE {fmt(t.qb.ngs_cpoe)}</p><small>{t.qb.n_dropbacks} dropbacks · depth chart only; backup flag unknown. Inactives unknown until T-90. Non-QB injury availability unknown; injuries never move a number automatically.</small></>}/>
 <Teams g={g} title="09 / Momentum · untested" render={t=><><b>Roll index {fmt(t.momentum.value)}</b><p>{Object.entries(t.momentum.components).map(([k,v])=>k.replaceAll("_"," ")+" z "+fmt(v)).join(" · ")}</p><small>Last {t.momentum.n_games} games versus own blended baseline. Predictive base rates: MEASURE. Eliminated status begins Week 12.</small></>}/>
 <Teams g={g} title="10 / Scoring composition and luck" render={t=><><p>Red zone TD {pct(t.composition.redzone_td_rate?.value)} · FG share {pct(t.composition.fg_share?.value)}</p><p>Defense/ST TD points per game {fmt(t.composition.def_st_td_points?.value)} (excludes extra points)</p><p>Turnover margin {fmt(t.composition.turnover_margin?.value)} · fumble recovery {pct(t.composition.fumble_recovery?.value)} · close games {t.composition.close_games?.wins} wins / {t.composition.close_games?.n}</p><small>Luck index: MEASURE. No stability study has qualified it to influence a number.</small></>}/>
 <NumberEntry key={id} g={g}/>{g.locks.map(l=><p key={l.market}><b>{l.phase} LOCK · {l.market} · {l.verdict.verdict}</b> {l.verdict.side} {l.verdict.line} · {new Date(l.locked_at).toLocaleString()}</p>)}
 <section className="suit-panel"><h2>Feedback / Human leans</h2><small>Regular season shown here; postseason remains separate in the CSV. Other board records remain separate. Multi-tag rows overlap.</small><div className="suit-scroll"><table><thead><tr><th>Person / tag</th><th>W–L–P</th><th>Mean CLV</th><th>Confidence Brier</th><th>Number Brier</th><th>Better predictor</th></tr></thead><tbody>{rows.map(r=><tr key={r.person+r.tag}><th>{r.person} / {r.tag}</th><td>{r.wins}–{r.losses}–{r.pushes}</td><td>{fmt(r.mean_clv_points)}</td><td>{r.brier_confidence===null?"After 50 graded":fmt(r.brier_confidence,4)}</td><td>{r.brier_number===null?"After 50 graded":fmt(r.brier_number,4)}</td><td>{r.better_predictor||"After 50 graded"}</td></tr>)}</tbody></table></div><h3>Hit rate by confidence</h3><div className="suit-two">{["Gabe","Jarrett"].map(p=><div key={p}><b>{p}</b>{board.feedback.rows.filter(r=>r.person===p&&r.tag==="ALL"&&r.population==="REGULAR"&&r.week==="ALL"&&r.phase==="ALL"&&r.input_class==="ALL"&&r.confidence!=="ALL").map(r=><p key={r.confidence}>Level {r.confidence}: {pct(r.hit_rate)} · {r.wins}–{r.losses}–{r.pushes}</p>)}</div>)}</div>{board.feedback.calibration.length>0&&<div><h3>Observed calibration / prior weight 20</h3>{board.feedback.calibration.map(c=><p key={c.person+c.population+c.level}>{c.person} · {c.population} · level {c.level}: provisional {pct(c.provisional)}, observed {pct(c.observed)} ({c.n}), shrunk estimate {pct(c.posterior)}</p>)}<small>New maps are versioned weekly and applied only to future entries.</small></div>}</section>
 <details className="suit-panel"><summary>Evidence, coverage and methods</summary><p>Weeks 1–5: prior season weight (6 − week) / 5; current season (week − 1) / 5. Week 6 onward current only. Missing current games retain prior-season data and PARTIAL status. Ridge penalty 1. Pressure coverage can be prior-season only.</p><p>No MEASURE or UNMEASURED component changes a number. No autonomous picks. Rank unavailable where no valid sample exists.</p><small>Prepared {board.as_of} · distribution {board.distribution_hash.slice(0,8)}</small>{Object.entries(board.source_hashes).map(([k,v])=><p key={k}><code>{k} · {v.slice(0,8)}</code></p>)}</details></main>;
}
