"use client";
import {createContext,useContext,useSyncExternalStore,useState,type ReactNode} from 'react';
import type {LockedBoard,LockedGame} from '../domain/locked-board';
import {ticketBooks,type Ticket,type TicketLeg,type TicketInput} from '../domain/tickets';
const fmt=(n:number)=>`${n>0?'+':''}${n}`;
const Context=createContext<{add:(l:TicketLeg)=>void}|null>(null);
export function TicketPick({game,market,side,line,book,price,children}:{game:LockedGame;market:'spreads'|'totals';side?:string;line?:number;book?:string;price?:number;children:ReactNode}){
 const ctx=useContext(Context);const code=side===game.home_team?(game.home_abbr==='LA'?'LAR':game.home_abbr):side===game.away_team?(game.away_abbr==='LA'?'LAR':game.away_abbr):side;
 const q=game.quote_pairs?.find(q=>q.market===(market==='spreads'?'spread':'total')&&q.side===code&&q.point===line&&q.book===book&&q.americanPrice===price);
 if(!ctx||!q||game.status==='FINAL')return <>{children}</>;
 return <button className="ticket-pick" title="Add this selection to the bet slip" onClick={()=>ctx.add({game_id:game.game_id,market:q.market as 'spread'|'total',side:q.side,line:q.point!,price:q.americanPrice,book:q.book,captured_at:q.capturedAt})}>{children} <small>＋</small></button>;
}
export function GameTicketPicker({game}:{game:LockedGame}){
 const ctx=useContext(Context);const [choice,setChoice]=useState('');if(!ctx||game.status==='FINAL')return null;
 const quotes=game.quote_pairs?.filter(q=>q.market==='spread'||q.market==='total')??[];
 return <div className="ticket-other"><label>Choose another side or book <select value={choice} onChange={e=>setChoice(e.target.value)}><option value="">Select a captured offer</option>{quotes.map((q,i)=><option key={i} value={i}>{q.side} {q.point} · {ticketBooks[q.book]??q.book} {fmt(q.americanPrice)}</option>)}</select></label><button disabled={choice===''} onClick={()=>{const q=quotes[Number(choice)];ctx.add({game_id:game.game_id,market:q.market as 'spread'|'total',side:q.side,line:q.point!,price:q.americanPrice,book:q.book,captured_at:q.capturedAt});}}>Add to slip</button></div>;
}
type Grade={ticket_id:string;outcome:string;profit_cents:number|null;legs:{outcome:string|null}[]};
const subscribeCode=(notify:()=>void)=>{window.addEventListener('storage',notify);return()=>window.removeEventListener('storage',notify);};
export function TicketProvider({board,children}:{board:LockedBoard|null;children:ReactNode}){
 const [legs,setLegs]=useState<TicketLeg[]>([]),[type,setType]=useState<TicketInput['type']>('single'),[price,setPrice]=useState(''),[stake,setStake]=useState('50'),[codeOverride,setCode]=useState<string|undefined>(undefined),[recordClass,setRecordClass]=useState<'paper'|'executed'>('paper');
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[saved,setSaved]=useState<Ticket[]>([]),[grades,setGrades]=useState<Grade[]>([]),[id,setId]=useState('');
 const storedCode=useSyncExternalStore(subscribeCode,()=>sessionStorage.getItem('nfl-team-edit-code')??'',()=> '');const code=codeOverride??storedCode;
 const add=(l:TicketLeg)=>{if(legs.some(x=>x.game_id===l.game_id&&x.market===l.market)){setMessage('That game and market are already in the slip. Remove the leg to change sides.');setOpen(true);return;}if(legs.length&&legs[0].book!==l.book){setMessage('Use one sportsbook for every leg. Choose another offer in Analytics.');setOpen(true);return;}setLegs([...legs,l]);if(legs.length&&type==='single')setType('parlay');setId(crypto.randomUUID());setPrice('');setOpen(true);setMessage('');};
 const load=async()=>{setBusy(true);try{const r=await fetch('/api/tickets',{headers:{authorization:`Bearer ${code}`},cache:'no-store'});const d=await r.json() as {error?:string;tickets:Ticket[];grades?:Grade[]};if(!r.ok)throw Error(d.error);sessionStorage.setItem('nfl-team-edit-code',code);setSaved(d.tickets);setGrades(d.grades??[]);setMessage('Locked picks loaded.');}catch(e){setMessage(String(e instanceof Error?e.message:e));}finally{setBusy(false);}};
 const lock=async()=>{setBusy(true);try{const input:TicketInput={id,type,book:legs[0].book,stake_cents:Math.round(Number(stake)*100),price:type==='single'?legs[0].price:Number(price),record_class:recordClass,legs};const r=await fetch('/api/tickets',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${code}`},body:JSON.stringify(input)});const d=await r.json() as {error?:string;ticket:Ticket};if(!r.ok)throw Error(d.error);sessionStorage.setItem('nfl-team-edit-code',code);setSaved(s=>[d.ticket,...s.filter(x=>x.id!==d.ticket.id)]);setLegs([]);setPrice('');setType('single');setId(crypto.randomUUID());setMessage('LOCKED — your ticket is saved.');}catch(e){setMessage(e instanceof Error?e.message:'Lock failed. Your slip is still here; retry is safe.');}finally{setBusy(false);}};
 return <Context.Provider value={{add}}>{children}<style>{`.ticket-pick{background:none;border:0;padding:0;color:inherit;font:inherit;font-weight:700;text-align:left;cursor:pointer}.ticket-pick:hover{color:#c3ef93;text-decoration:underline}.ticket-pick small{color:#c3ef93}.ticket-bar{position:fixed;bottom:12px;right:20px;z-index:50;background:#b6ed86;color:#101b12;border:0;border-radius:5px;padding:11px 18px;font-weight:700;cursor:pointer}.ticket-panel{position:fixed;z-index:60;right:12px;bottom:12px;width:min(420px,calc(100vw - 24px));max-height:85vh;overflow:auto;background:#13261c;color:#edf4ee;border:1px solid #67806d;border-radius:8px;padding:16px;box-shadow:0 8px 30px #0009;font-size:13px}.ticket-panel header{display:flex;justify-content:space-between}.ticket-panel h3{margin:0}.ticket-panel label{display:block;margin:9px 0}.ticket-panel input,.ticket-panel select,.ticket-panel button,.ticket-other select,.ticket-other button{font:inherit;border:1px solid #617967;border-radius:3px;background:#102017;color:#eef6ef;padding:7px}.ticket-panel input,.ticket-panel select{max-width:100%;margin-left:6px}.ticket-panel ul{padding-left:18px}.ticket-panel li{margin:10px 0}.ticket-panel .ticket-lock{background:#b6ed86;color:#102017;font-weight:700;width:100%;margin-top:10px}.ticket-panel button:disabled{opacity:.4}.ticket-panel small{color:#b4c7ba}.ticket-receipt{border-top:1px solid #48614f;margin-top:12px;padding-top:10px}.ticket-other{font-size:11px;display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin:10px 0}.ticket-other select{display:block;max-width:100%;margin-top:4px}`}</style>
 {!open?<button className="ticket-bar" onClick={()=>setOpen(true)}>Bet slip{legs.length?` (${legs.length})`:' / Locked picks'}</button>:<aside className="ticket-panel" aria-label="Bet slip"><header><h3>Bet slip</h3><button onClick={()=>setOpen(false)} aria-label="Close bet slip">×</button></header>
 <label>Team code <input type="password" value={code} autoComplete="off" onChange={e=>setCode(e.target.value)}/></label><button disabled={!code||busy} onClick={()=>void load()}>Show locked picks</button>
 {!!legs.length&&<><label>Ticket <select value={type} onChange={e=>{setType(e.target.value as typeof type);setId(crypto.randomUUID());setPrice('');}}><option value="single">Single</option><option value="parlay">Parlay</option><option value="teaser">6-point teaser</option></select></label><b>{ticketBooks[legs[0].book]}</b><ul>{legs.map((l,i)=>{const moved=l.line+(l.market==='spread'||l.side==='Under'?6:-6);return <li key={l.game_id+l.market}>{l.side} {l.market==='spread'?fmt(l.line):l.line} · {fmt(l.price)}{type==='teaser'&&<b> → {l.market==='spread'?fmt(moved):moved}</b>}<br/><small>{board?.games.find(g=>g.game_id===l.game_id)?.away_abbr} @ {board?.games.find(g=>g.game_id===l.game_id)?.home_abbr}</small> <button aria-label={`Remove ${l.side}`} onClick={()=>{setLegs(legs.filter((_,j)=>j!==i));setId(crypto.randomUUID());}}>Remove</button></li>;})}</ul>
 {type==='single'?<p>Ticket odds: {fmt(legs[0].price)}</p>:<label>Sportsbook ticket odds <input type="number" placeholder="e.g. -120 or +260" value={price} onChange={e=>{setPrice(e.target.value);setId(crypto.randomUUID());}}/><small>Use the combined price shown by the book.</small></label>}
 <label>Stake $ <input type="number" min="0.01" max="100" step="0.01" value={stake} onChange={e=>{setStake(e.target.value);setId(crypto.randomUUID());}}/></label><small>$50 per unit · $100 maximum per ticket and per game across locked tickets.</small>
 <label>Record as <select value={recordClass} onChange={e=>{setRecordClass(e.target.value as typeof recordClass);setId(crypto.randomUUID());}}><option value="paper">Pick / paper ticket</option><option value="executed">Already placed at sportsbook</option></select></label>
 <button className="ticket-lock" disabled={busy||!code||!legs.length||type!=='single'&&!price} onClick={()=>void lock()}>{busy?'Saving…':'Lock ticket'}</button><small>Locks your shared record. Ticket prices and selections are saved together.</small></>}
 {!legs.length&&<p>Click a spread or total on the board to start a ticket.</p>}{message&&<p role="status">{message}</p>}
 {saved.map(t=>{const grade=grades.find(g=>g.ticket_id===t.id);return <div className="ticket-receipt" key={t.id}><b>{t.type.toUpperCase()} · {grade?.outcome??'LOCKED'}</b><p>{t.legs.map(l=>`${l.side} ${l.settlement_line}`).join(' + ')}</p><small>{ticketBooks[t.book]} {fmt(t.price)} · ${(t.stake_cents/100).toFixed(2)} · {t.record_class==='executed'?'Placed':'Paper'} · {new Date(t.locked_at).toLocaleString()}{grade?.profit_cents!=null?` · Net $${(grade.profit_cents/100).toFixed(2)}`:''}</small></div>;})}</aside>}</Context.Provider>;
}
