"""Render registered QB evidence from saved outputs, independently checking gate arithmetic."""
import collections,hashlib,json,math,sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];O=ROOT/'work/e-elo-qb-value-v2'
def ri(x):return int(math.copysign(math.floor(abs(x)+.5),x))
def run():
 gate=json.loads((O/'gate.json').read_text());data=json.loads((O/'oof.json').read_text());ref=json.loads((O/'value-data-ref.json').read_text());v=json.loads((ROOT/ref['values']['path']).read_text());maxdiff=0;qc={};production_probs={}
 for name,rows in data.items():
  mae=math.fsum(abs(r['actual_'+s]-r[s]) for r in rows for s in ['away','home'])/(2*len(rows));maxdiff=max(maxdiff,abs(mae-gate['summary'][name]['team_mae']));hits=collections.defaultdict(list);probs=[];ys=[]
  for year in range(2017,2026):
   prior=[r for r in rows if r['season']<year];errs={k:[] for k in ['margin','total']}
   for r in prior:
    he=r['actual_home']-r['home'];ae=r['actual_away']-r['away'];errs['margin'].append(ri(he-ae));errs['total'].append(ri(he+ae))
   for r in rows:
    if r['season']!=year:continue
    for k in ['margin','total']:
     pm=r['home']-r['away'] if k=='margin' else r['home']+r['away'];actual=r['actual_home']-r['actual_away'] if k=='margin' else r['actual_home']+r['actual_away'];e=np.array(errs[k]);center=ri(pm)
     for lev in [50,80]:
      lo,hi=np.quantile(e,[(1-lev/100)/2,1-(1-lev/100)/2],method='inverted_cdf')+center;hits[k+'_'+str(lev)].append(lo<=actual<=hi)
     if k=='margin':probs.append(float(np.mean(e+center>0)+.5*np.mean(e+center==0)));ys.append(1 if actual>0 else 0 if actual<0 else .5)
  for k,h in hits.items():assert abs(np.mean(h)-gate['coverage'][name][k]['coverage'])<1e-12,(name,k)
  qc[name]={'independent_team_mae':mae,'coverage_recomputed':True,'games':len(rows)};production_probs[name]={'games':len(probs),'brier':float(np.mean((np.array(probs)-ys)**2))}
 assert maxdiff<1e-12
 result={'max_mae_difference':maxdiff,'candidates':qc,'production_score_residual_probability':production_probs,'arithmetic_separate_implementation':True};(O/'gate-recomputation.json').write_text(json.dumps(result,indent=2)+'\n')
 reg=json.loads((O/'registration.json').read_text());lines=[gate['premise'],'','# E-ELO-QB: REJECTED','','REVIEW REQUESTED — fixed conventions: common sixteen-week league prior; unknown selected starters retain inactive adjustment; released HFA is the current gate control alongside original c; scale uses the valid nonnegative Elo numerical domain; oracle holds rule-fitted scales fixed; incomplete CPOE windows make combined VALUE secondary/partial. Alternatives are listed in the hashed PLAN.md. No gate or numerical candidate was changed after results.','','The specified QB VALUE does not reach the 1% team-MAE gate. Neither usable candidate clears it in any individual season, against the released HFA control. Coverage passes. HFA remains deployed; QB adjustment remains inactive.','','## Accepted reconciliation','','Full stated starter rule: 90.96% on the reproduced common sample. The user reconciles 90.87% on their four-season selection and reports that the injury override is correct 30/40 times; the former 89.4% omitted the override and counted declines as misses. Their 2,442 versus our 2,806 regression rows reflect their additional prior-season QB-history filter. Our 0.8% in-sample gain is descriptive, not an OOF gate. These differences are resolved, with original records preserved.','','## Gate table','','All 2,639 regular-season games, 2016–2025; 5,278 team outcomes. Positive gain means lower error. MAE uses every game; coverage uses 2,383 games in 2017–2025 with each candidate’s own earlier OOF residuals. 2016 has no earlier OOF calibration in this lineage and is explicitly unscored for coverage.','','| Candidate | Team MAE | Gain vs released HFA | Gain vs original c | Paired 95% gain, points | Coverage | Decision |','|---|---:|---:|---:|---|---|---|']
 labels={'c_original':'c: original control (superseded)','deployed_hfa':'Released HFA control','a_qb':'a: QB EPA','b_qb_hfa':'b: QB EPA + HFA','oracle_a':'Oracle a — unavailable identity','secondary_combined':'EPA+CPOE — SECONDARY/PARTIAL'}
 for k,m in gate['summary'].items():
  c=gate['comparison'][k]['deployed_hfa'];old=gate['comparison'][k]['c_original'];iv=c['paired_team_point_gain_interval'];decision='REJECTED' if k in ['a_qb','b_qb_hfa'] else 'DIAGNOSTIC' if k in ['oracle_a','secondary_combined'] else 'CONTROL';lines.append(f"| {labels[k]} | {m['team_mae']:.6f} | {100*c['relative_team_mae_improvement']:.3f}% | {100*old['relative_team_mae_improvement']:.3f}% | [{iv['lower95']:.6f}, {iv['upper95']:.6f}] | PASS | {decision} |")
 lines+=['','Paired uncertainty uses 10,000 resamples of within-season three-week blocks, retaining both teams of every game. Oracle and CPOE secondary cannot promote. The original c comparison is retained for registration continuity; only released HFA is authoritative for the gate.','','## Coverage','','| Candidate | Margin 50 | Margin 80 | Total 50 | Total 80 |','|---|---:|---:|---:|---:|']
 for k,cv in gate['coverage'].items():lines.append('| '+labels[k]+' | '+' | '.join(f"{100*cv[x]['coverage']:.2f}%" for x in ['margin_50','margin_80','total_50','total_80'])+' |')
 lines+=['','## Elo-component evidence','','These probabilities are Elo’s own logistic forecasts. The site uses score-plus-residual probabilities; their independently recomputed Brier scores are recorded separately in gate-recomputation.json.','','| Candidate | Elo margin MAE | Signed margin bias | Actual-on-projected slope | Elo win Brier |','|---|---:|---:|---:|---:|']
 for k,m in gate['own_elo'].items():lines.append(f"| {labels[k]} | {m['mae']:.6f} | {m['bias']:+.6f} | {m['slope']:.6f} | {m['win_brier']:.6f} |")
 lines+=['','Win reliability by bin (predicted home probability / actual home win share; ties count half):','','| Candidate | Bin lower | Games | Predicted | Actual |','|---|---:|---:|---:|---:|']
 for k,m in gate['own_elo'].items():
  for b in m['reliability']:lines.append(f"| {labels[k]} | {b['lower']:.1f} | {b['n']} | {b['predicted']:.4f} | {b['actual']:.4f} |")
 lines+=['','## Seasonal team MAE and scale','','| Season | HFA control MAE | a gain | b gain | Oracle gain | a fitted s | b fitted s | CPOE secondary s | Training games per s |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
 # Actual games used by scale objective: 2014 onward, before outer season; no target-season fit.
 schedule=json.loads((ROOT/'work/projection-v1/data/schedule-bb16d18a8a2b19849a448e2d62f4c3c0838f9c4c2b466b36f331339367db9fec.json').read_text())
 for year in range(2016,2026):
  y=str(year);c=gate['by_season']['deployed_hfa'][y]['team_mae'];ps={k:next(p for p in gate['scales'][k] if p['season']==year) for k in ['a_qb','b_qb_hfa','secondary_combined']};ng=sum(g['game_type']=='REG' and int(g['season'])<year and g.get('home_score') not in ('',None) for g in schedule);gains=[100*(1-gate['by_season'][k][y]['team_mae']/c) for k in ['a_qb','b_qb_hfa','oracle_a']];lines.append(f"| {year} | {c:.6f} | {gains[0]:+.3f}% | {gains[1]:+.3f}% | {gains[2]:+.3f}% | {ps['a_qb']['scale']:.6f} | {ps['b_qb_hfa']['scale']:.6f} | {ps['secondary_combined']['scale']:.6f} | {ng} |")
 lines+=['','Exactly one fitted quantity per candidate/outer season: s. CPOE’s 1.0 weight is fixed, not fitted. EPA primary rawVALUE=attempt-weighted EPA/attempt. Secondary rawVALUE=EPA/attempt+1.0×CPOE/100. Both starter/team values are multiplied by s before the unchanged 3.3 difference multiplier. Ridge coefficients are the existing production refits, not additional QB parameters. Full brackets, losses, domain exclusions and fit lineage are in gate.json and ridge-lineage.json.','','The scale is unstable across seasons: a ranges 4.47–77.40; b ranges 14.33–69.25. This is a finding, not a license to select a favorable scale. No outer-season outcomes select these values.','','## Availability','','| Season | Team games | EPA VALUE available | Combined VALUE available | UNTIMESTAMPED identity | ROOKIE_PRIOR |','|---|---:|---:|---:|---:|---:|']
 for y in range(2016,2026):
  rr=[r for r in v if r['season']==y];lines.append(f"| {y} | {len(rr)} | {sum(r['values']['rule']['epa']['difference'] is not None for r in rr)} | {sum(r['values']['rule']['combined']['difference'] is not None for r in rr)} | {sum(r['UNTIMESTAMPED'] for r in rr)} | {sum(r['values']['rule']['ROOKIE_PRIOR'] for r in rr)} |")
 oracle_gain=gate['summary']['a_qb']['team_mae']-gate['summary']['oracle_a']['team_mae'];lines+=['',f'Primary EPA values are available for 5,271/5,278 team games; seven missing starters retain explicitly inactive adjustment, without dropping games. Combined windows are unavailable for 422 team games. Independent recomputation checked 49,857 means and every qualifying 16-game selection; maximum arithmetic difference 2.22e-16. No window reaches the 2000 history boundary.','',f'Perfect retrospective identification lowers team MAE by a further {oracle_gain:.6f}points versus the rule (about{100*oracle_gain/gate["summary"]["a_qb"]["team_mae"]:.3f}%). It still falls well below 1%. Under this specific VALUE formula, identification errors alone do not explain the failure to promote. That does not reject other valuation models, a different mapping into points, or the broader usefulness of QB evidence. Actual attempt leader is itself an oracle definition, not proof of the announced pregame starter.','','## Current season and execution','','No graded 2026 game was issued by the newly released HFA lineage: it was released after the Thursday game. The existing as-issued sample is 8 games from projection-v2-172f3e04-a39aa883, 6 from projection-v3-b7a84dbe-2b5d9d0f, and 1 from projection-v2.w2. Two other Week 1 records are retrospective. These are not pooled as new-lineage validation and are not rewritten. Prospective evidence requires games locked and graded under projection-v2.hfa1.','',f'The numerical gate took {gate["elapsed_seconds"]:.1f}seconds on one worker, below 45 minutes. The original and released controls reproduce within 1e-10 on every eligible game. An independent implementation reproduces all team MAEs and every coverage count. No fitting occurs when rendering this report. No paid API credits used.','',f'Preregistration SHA256: `{gate["registration_sha256"]}`. Released HFA fit: `f7fc497ee581c3a948388891904b52669e345bae1a61c684281034505b5840e4`.','', 'Least sure of: how much a fully observed CPOE window would change the conditional valuation result; this run does not fill missing CPOE.','','Confidence: high — rejection of this specified QB adjustment holds across seasons and survives the obvious comparisons: original versus released control, HFA combination, retrospective oracle, and the disclosed partial CPOE alternative. Move down to medium if an independent authoritative replay exposes a material window or scale-fitting discrepancy. This confidence does not extend to rejecting QB value in general.']
 lines[-3:-3]=['COMMIT c861e82504505ee5707bce369028a2b00f59618f (pushed registration and numerical evaluation code).', '', 'Tests: 251 passed — 218 standing checks and 33 focused checks, including frozen Elo separation, chronology, exact prior-window selection, scale-fit future exclusion, updated authority rejection, and HFA lineage retention across a weekly refit.', '']
 (O/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':run()
