"""Read-only numeric diagnosis and publication evidence reports."""
import collections,datetime as dt,gzip,hashlib,json,statistics,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from engine.projection_v3.qualify import read,save,load_prepared
from engine.projection_v3.card import make_card
from engine.projection.train import paired
from engine.projection.distribution import pmf,quantile,integer
from engine.projection_v3.personnel import NAMES

def run():
 w=ROOT/'work/projection-v3';record=read(json.loads((w/'record-ref.json').read_text()));artifact=read(record['fit']);shapes=read(artifact['shapes']);prepared,_,_=load_prepared();rows=prepared['none'];v2=read(json.loads((ROOT/'work/projection-v2/record-ref.json').read_text()))
 assert read(record['baseline_oof'])==read(v2['baseline_oof'])
 numeric={}
 for name,rec in [('v2',v2),('v3',record)]:
  f=read(rec['fit']);s=read(f['shapes'])['margin'];mass=pmf(s,0);mean=sum(v*p for v,p in mass.items());numeric[name]={'version':f['version'],'residual_mean':mean,'residual_median':quantile(mass,.5),'home_share_at_zero_score_margin':sum(p for v,p in mass.items() if v>0)+mass.get(0,0)/2,'tie_mass_at_zero_margin':mass.get(0,0),'observations':s['n'],'center_rounding':'nearest integer, half away from zero','centered':False,'semantics':'home_win_probability = P(home score margin > 0) + 0.5 P(margin = 0); not outright win probability'}
 current=json.loads(gzip.decompress((w/'current-features.json.gz').read_bytes()));pair=paired(current)['2026_01_BAL_IND'];game={**pair['home']['game'],'kickoff_at':'2026-09-13T17:00:00+00:00','cutoff_at':'2026-09-13T15:45:00+00:00'};now=dt.datetime.now(dt.timezone.utc);card=make_card(game,pair,artifact,shapes,now.isoformat(),evidence='RETROSPECTIVE');card['status']='DIAGNOSTIC_NOT_ISSUED';cardref=save('bal-ind-diagnostic',card)
 groups=collections.defaultdict(lambda:{'away':0.,'home':0.})
 for side in ['away','home']:
  for c in card['contributions'][side]:groups[c['group']][side]+=c['points']
 ranked=sorted([{'group':g,**v,'home_margin':v['home']-v['away']} for g,v in groups.items()],key=lambda x:(-abs(x['home_margin']),x['group']))
 coverage=[]
 for y in range(2016,2026):
  rr=[r for r in rows if r['season']==y];coverage.append({'season':y,'team_rows':len(rr),'measurements':{k:sum(r['features'][k] is not None for r in rr) for k in NAMES},'starter_rules':dict(collections.Counter(r['personnel']['qb_identity_rule'] for r in rr)),'chart_status':dict(collections.Counter(r['personnel']['qb_chart_status'] for r in rr))})
 p=card['projection'];m=pmf(shapes['margin'],p['margin']);numeric['bal_ind_v3']={'projected_home_margin':p['margin'],'rounded_margin':integer(p['margin']),'distribution_mean_margin':sum(v*z for v,z in m.items()),'distribution_median_margin':quantile(m,.5),'home_outright_win':p['home_win_probability']-p['tie_probability']/2,'tie_probability':p['tie_probability'],'home_tie_split_share':p['home_win_probability'],'conflict':card['score_probability_conflict']}
 data=read(record['source_manifest']['personnel']);audit={'version':artifact['version'],'baseline_population_unchanged':True,'coverage':coverage,'probability_audit':numeric,'bal_ind':cardref,'contribution_ranking':ranked,'pressure_overlap_by_year':[a for a in data['audit'] if a.get('kind')=='pbp'],'injury_schemas':data['injuries'],'new_groups':{g:read(record['qualification'])[-1]['marginal'][g] for g in ['quarterback','pressure','career_kicking']},'v2_comparison':{'v2_adaptive':v2['release_gate']['candidate_mae'],'v3_adaptive':record['release_gate']['candidate_mae'],'superiority_to_v2':False}}
 ref=save('audit',audit);(w/'audit-ref.json').write_text(json.dumps(ref,indent=2)+'\n')
 lines=['# BAL at IND — new-fit diagnostic',f"\nVersion: {artifact['version']}. RETROSPECTIVE diagnostic created {now.isoformat()}; never issued or substituted for the original lock.",f"\nProjected BAL {p['away_points']:.3f}, IND {p['home_points']:.3f}; IND-minus-BAL margin {p['margin']:+.3f}; total {p['total']:.3f}. Winner field: {card['winner']}, tie-split share {card['winner_probability']:.2%}. Model tie mass {p['tie_probability']:.2%}.",'\n| Ranked group | BAL points | IND points | IND-minus-BAL contribution |','|---|---:|---:|---:|']
 for x in ranked:lines.append(f"| {x['group']} | {x['away']:+.4f} | {x['home']:+.4f} | {x['home_margin']:+.4f} |")
 lines+=['\n## Supporting and opposing football terms',*['- '+x for x in card['why']['lines']],'- '+card['why']['against'],'\n## Requested inputs (measured; zero fitted weight after qualification)','\n| Input | BAL measurement | IND measurement | Fitted contribution |','|---|---:|---:|---:|']
 for n in NAMES:
  vals=[pair[s]['features'][n] for s in ['away','home']];lines.append(f"| {NAMES[n]} | "+' | '.join('unavailable' if v is None else f'{v:.5f}' for v in vals)+' | 0 |')
 lines+=['\nThe original BAL–IND v2 lock and its first grade remain unchanged. QB and kicker identities, dated chart sources, prior-game fallback and career-history qualification are preserved in the diagnostic JSON. No current-game participation was used.',f"\nProbability audit: residual mean {numeric['v3']['residual_mean']:+.3f}, median {numeric['v3']['residual_median']:+d}. At equal projected scores the home tie-split share is {numeric['v3']['home_share_at_zero_score_margin']:.2%}. This uncentered residual distribution plus integer rounding can select a different winner from the team-score leader. We retained the registered method and report the mismatch; no score was altered to justify a winner."]
 (w/'BAL-IND.md').write_text('\n'.join(lines)+'\n')
 extra=['\n## Requested personnel and pressure inputs','\nQB, pressure and kicker measurements are now implemented. QB passed the marginal screen (1.039% team-MAE gain), but failed conditional elimination (-0.259%). Pressure failed the marginal screen (0.262%, below 0.5%, and total MAE worsened). Career kicking failed (-0.0756% team gain). Continuity/referee remain zero. Elo also narrowly failed the conditional 0.5% gate (0.4815%) in the expanded candidate set; simultaneous removal follows the registered protocol. The future fit retains only calibration on the mandatory PPD/pace baseline.','\n### Prior v2 comparison','\n| Target | V2 adaptive MAE | V3 adaptive MAE |','|---|---:|---:|']
 for k in ['team_points','margin','total']:extra.append(f"| {k} | {v2['release_gate']['candidate_mae'][k]:.6f} | {record['release_gate']['candidate_mae'][k]:.6f} |")
 extra+=['\nV3 passes the raw-baseline gate; it is worse than v2 on these historical metrics. Neither record is a fresh untouched holdout.','\n### Source qualification and missing evidence','\nKicker IDs existed in raw PBP; the previous feature code explicitly forced career bands to null because it only had team aggregates. New career ledgers follow selected kicker IDs across teams, including postseason and garbage time, using only earlier games. Zero-attempt bands stay null. Careers crossing the 1999 boundary are flagged and unavailable rather than mislabeled complete. Career QB starts use the first-dropback proxy, not an official starts feed. Backup means replacement of the historical team incumbent, not an official injury designation.','\nHistorical weekly charts (2009–2024) lack proven original issuance. Timestamped charts are filtered strictly before T75; current receipt also must precede T75. Injury files contain no explicit replacement-starter field, so no injury override was fabricated. The prior-game fallback is flagged row by row. Current-game schedule QB IDs are not used. All sources were hashed; public downloads used no Odds API credits.','\nPressure uses the literal qb_hit+sack sum. Most seasons contain overlapping hit/sack flags, so this is a weighted event proxy, not the fraction of distinct pressured plays. The audit records overlap per season. The absence of overlap in 2003–2005 warrants source-coding caution; those years do not enter the 2015–2025 pressure features used by this fit.','\n### Input coverage','\nCounts are measured team-game rows; missing input values contribute zero correction, not a measured zero.','\n| Season | Team rows | QB EPA / CPOE / starts / backup | Pressure generated / allowed | Career FG short / medium / long |','|---|---:|---|---|---|']
 for c in coverage:
  v=c['measurements'];extra.append(f"| {c['season']} | {c['team_rows']} | "+' / '.join(str(v[k]) for k in ['qb_epa','qb_cpoe','qb_career_starts','qb_backup'])+' | '+' / '.join(str(v[k]) for k in ['pressure_generated','pressure_allowed'])+' | '+' / '.join(str(v[k]) for k in ['career_fg_short','career_fg_medium','career_fg_long'])+' |')
 extra+=['\n### Probability diagnosis',f"\nV2 margin residual mean/median: {numeric['v2']['residual_mean']:+.4f}/{numeric['v2']['residual_median']:+d}; home tie-split share at equal scores: {numeric['v2']['home_share_at_zero_score_margin']:.2%}. V3: {numeric['v3']['residual_mean']:+.4f}/{numeric['v3']['residual_median']:+d}, {numeric['v3']['home_share_at_zero_score_margin']:.2%}. The stored residuals are not centered; rounding the projected margin creates probability steps. Mean point estimates therefore disagree with residual-based winner direction near zero. The field includes half of modeled tie mass, so it is not outright P(win). The reader now labels tie splitting, and new conflicting cards carry an explicit disagreement note. No recentering, symmetrization, score adjustment or probability-method change was made.",'\n[BAL–IND ranked contribution report](BAL-IND.md). Full counts and numeric audit: '+Path(ref['path']).name+'.','\nSource documentation: [nflfastR fields](https://nflfastr.com/reference/fast_scraper.html), [nflverse update and depth-chart availability](https://nflreadr.nflverse.com/articles/nflverse_data_schedule.html).']
 with (w/'report.md').open('a') as f:f.write('\n'.join(extra)+'\n')
 print(json.dumps({'version':artifact['version'],'audit':ref,'bal_ind_projection':p,'probability_audit':numeric}))
if __name__=='__main__':run()
