"""Report the preserved v1 reference without changing the registered v2 gate."""
import json,sys
from pathlib import Path
from scripts.reference_reports import report_file
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from engine.projection_v2.qualify import read,save,paired
from engine.projection.model import hash_value

def main():
 work=ROOT/'work/projection-v2';r=read(json.loads((work/'record-ref.json').read_text()));v1=read(read(r['fit'])['v1_source_fit']);shape=read(v1['shapes']);sha=shape['margin']['source_hash'];ref={'path':'work/projection-v1/oof-predictions-'+sha+'.json','sha256':sha};rows=read(ref);p=paired(rows,[x['projected_points'] for x in rows]);ids={x['game_id'] for x in read(r['oof'])};assert ids=={x['game_id'] for x in p};mae={k:sum(x['loss'][i] for x in p)/len(p) for k,i in [('team_points',0),('margin',1),('total',2)]};value={'v2_experiment':json.loads((work/'record-ref.json').read_text()),'v1_oof':ref,'paired_n':len(p),'v1_mae':mae,'v2_adaptive_mae':r['release_gate']['candidate_mae'],'v2_final_subset_development_mae':r['final_subset_development']['candidate_mae'],'interpretation':'Context only, not a new release gate. Final-subset historical results reuse the subset selected through 2025 and are development evidence. The adaptive v2 procedure includes three initial baseline-only seasons and does not establish superiority to v1.'};out=save('v1-context',value);p=work/'report.md';report_file(p).write_text(p.read_text()+f"\n## Preserved v1 context\n\n[Comparison record]({Path(out['path']).name}), {len(ids)} identical games. This does not alter the preregistered release gate.\n\n| Forecast | Team MAE | Margin MAE | Total MAE |\n|---|---:|---:|---:|\n"+'\n'.join('| '+label+' | '+' | '.join(f'{m[k]:.4f}' for k in ['team_points','margin','total'])+' |' for label,m in [('V1 historical forecasts',mae),('V2 adaptive qualification',value['v2_adaptive_mae']),('V2 final subset, development only',value['v2_final_subset_development_mae'])])+"\n\nV2 qualifies against the raw football baseline. It does not establish superior accuracy to v1. Its adaptive record includes the first three seasons with insufficient prior group-validation history, so those forecasts use the baseline only. The final subset's historical performance is reported separately because choosing that subset used the whole development period.\n");print(json.dumps(value))
if __name__=='__main__':main()
