"""Render evidence audit tables from pinned ledger. No fitting."""
import json,collections,hashlib
from pathlib import Path
from scripts.qb_evidence_review import O,ROOT,compare,metrics,write

def run():
 g=json.loads((O/'game-ledger.json').read_text());z=json.loads((O/'changed-team-ledger.json').read_text());r=json.loads((O/'results.json').read_text());cross=json.loads((O/'source-cross-checks.json').read_text());ann=json.loads((O/'announcement-qualification.json').read_text());dis=json.loads((O/'independent/disputed-primary-identities.json').read_text())
 stable=[x for x in g if x['starter_group']=='STABLE'];changed=[x for x in g if x['starter_group']=='CHANGED'];bad={x['game_id'] for x in dis};screen={x['game_id'] for x in cross['mismatches']}
 extra={'three_verified_disputes_excluded':compare([x for x in changed if x['game_id'] not in bad],[x for x in stable if x['game_id'] not in bad]),'all_pbp_disagreements_excluded':compare([x for x in changed if x['game_id'] not in screen],[x for x in stable if x['game_id'] not in screen])}
 liberal={(x['game_id'],x['team']) for x in ann['accepted']}
 for a in ann['unaccepted']:
  if a['rejection']=='PUBLISHED_OR_CURRENT_REVISION_AFTER_T75':liberal.add((a['game_id'],a['team']))
 extra['liberal_original_publication_sensitivity_NOT_QUALIFIED']=compare([x for x in changed if any((v['game_id'],v['team']) in liberal for v in x['changed_teams'])],stable)
 write('additional-sensitivities.json',extra)
 queue=[]
 rejected={(a['game_id'],a['team']):a for a in ann['unaccepted']}
 for x in z:
  if x['announcement']:continue
  a=rejected.get((x['game_id'],x['team']))
  queue.append({'game_id':x['game_id'],'team':x['team'],'season':x['season'],'reason':a['rejection'] if a else 'PRIMARY_ANNOUNCEMENT_SEARCH_NOT_COMPLETED','reviewed_url':a['url'] if a else None,'next_evidence':'Official gamebook and contemporaneous primary announcement with pre-T75 content provenance; qualified historical QB value vintage if scoring quality gap.'})
 write('remaining-evidence-queue.json',queue)
 # Attribution and numerical table renderer.
 lines=['# E-QB-CHANGE evidence review v2','',
 'Status: PARTIAL EVIDENCE AUDIT; causal diagnosis UNRESOLVED. The original blanket-unknown conclusion is withdrawn; the complete primary-source search is not finished. No fit, new candidate, production change or promotion.', '',
 'Premise: authoritative deployed-lineage control `work/projection-v2w/deployed-oof-6a0238fcb08e5bfcf3a7daa6710e3c9cfb0f04b3c31dae77d3baa5f9b9956c10.json`; generated 2026-09-19 UTC; producing code `538ce1f424bfe794ecbccf64ccabc8e4e9bbfadc`; fit-lineage settings `8bd585610049c63e30aea2e675f61cd6e65a5c22b268e87f89971bb3bffa246d`. Registry and bytes verified independently. Historical refits reproduce this lineage; they are not historical as-issued forecasts. Receipt approximates provider availability from kickoff plus four hours and hourly retries; exact historical provider delays are not observed.', '',
 '**REVIEW REQUESTED:** schedule-QB versus literal starter; original publication date versus later page revision. Preserve registered membership and show alternatives. The three independently verified identity disputes make it unsafe to call all 585 records actual starter changes. Favor conservative timestamp qualification without asserting that later retrieval alone invalidates publication.', '',
 '## Reproduction','', 'Bias is projected minus actual. Margin is home minus away. Team metrics include both teams of each game.', '', '| Group | Games | Team MAE | Team bias | Margin MAE | Margin bias |','|---|---:|---:|---:|---:|---:|']
 for k,v in r['groups'].items():lines.append(f"| {k} | {v['games']} | {v['team_mae']:.6f} | {v['team_bias']:+.6f} | {v['margin_mae']:.6f} | {v['margin_bias']:+.6f} |")
 lines+=['','These reproduce the previous pass; the correction concerns evidence and group interpretation, not arithmetic. There are 660 changed team-sides in 585 unique games.','',
 '## What the evidence establishes','',
 f"All 64 pinned personnel source receipts were inventoried; raw chart and injury files were read in full and hash checked. The path census contains {len(json.loads((O/'artifact-census.json').read_text()))} candidate artifact paths. The separate content/key inventory found {len(cross['lock_inventory'])} output lock JSON files, all outside the 2016–2025 historical population. No historical as-issued personnel lock was located. This does not establish that no external archive ever existed.", '',
 '2025: all 73 changed team-sides have an unambiguous eligible rank-1 chart. Independently, 46 match the schedule QB and 27 differ. These are listed identities, not confirmed starters or actual engine selections. Nine initially missing charts were an alias join bug (LA/LV/WAS versus LAR/OAK/WSH), corrected and independently reconciled before final tables. Earlier weekly chart availability is not proof of publication before T75.', '',
 'Sources: [nflverse depth-chart dictionary](https://nflreadr.nflverse.com/articles/dictionary_depth_charts.html) defines dt as record-load time; [data schedule](https://nflreadr.nflverse.com/articles/nflverse_data_schedule.html) documents capture cadence. Injury date_modified is modification time; injury status does not identify a replacement starter. Receipts are retrieval timestamps. Current article publication and modification metadata qualify only the cited content; no immutable revision archive has been captured.', '',
 f"Accepted announcements cover {len(ann['accepted'])} changed team-sides. {len(queue)} side records still need primary-source resolution or reconciliation. These are insufficient evidence, never 'not knowable'. Current search coverage is explicitly incomplete; source inventory is not a claim to have exhausted all primary archives.", '',
 '| Season | Changed games | Changed sides | Listed chart | Accepted prelock announcement | Actual engine locks | Qualified quality pairs |','|---|---:|---:|---:|---:|---:|---:|']
 for y,v in r['coverage'].items():lines.append(f"| {y} | {v['changed_games']} | {v['changed_team_sides']} | {v['chart_available']} | {v['knowledge_counts'].get('ESTABLISHED_BEFORE_T75',0)} | 0 | 0 |")
 lines+=['','## Verified disputes','']
 for x in dis:lines.append(f"- `{x['game_id']}` {x['team']}: schedule says {x['schedule_qb']}; primary evidence says {x['verified_qb']}. [Pregame evidence]({x['pregame_url']}); [postgame verification]({x['postgame_url']}).")
 lines+=['',f"The all-season schedule-versus-first-dropback screen flags {len(cross['mismatches'])} team-sides. Counts by season: {cross['mismatch_team_sides_by_season']}. First dropback itself is not necessarily the first snap; these are review flags, not automatically corrected labels. The first unnormalized screen undercounted these at 52; the final alias-normalized screen has 64.", '',
 '## Identification versus valuation','',
 'The verified fit retains calibration and Elo, with names baseline, elo, elo_difference. It has no retained QB-identity or QB-value coefficient. A displayed or reconstructed QB therefore cannot establish a direct QB adjustment in this deployed fit. This proves absence of an explicit retained adjustment, not that it caused an error or that team-strength inputs encode no quarterback effects.', '',
 'All actual historical engine-identity cells remain unobserved: correct, incorrect and identification-versus-value partitions cannot be measured from score-only replays. The ledger separately records the chart selector, not a full reconstructed production lock. No evidence establishes that a missing announcement was unknowable. No supported general causal diagnosis is available.', '',
 'Quality inventory: existing EPA/dropback is expected points per dropback; CPOE is completion percentage above model expectation; career-start count and backup flag are experience/role proxies, not independent quality values. Past-game EPA measurements for both QBs are now stored with count and strict completion cutoff. They remain RECONSTRUCTED_REVISED_PBP: prior outcomes do not establish that a later EPA/CPOE model vintage was available at historical lock. No market substitute, new value model, zero fill or outcome-selected band was used. A dated historical model/value release or auditable prior-only model lineage is needed to qualify these values. This is a vintage gap, not an assertion that historical passing statistics were unavailable.', '',
 '## Robustness','',
 '| Season | Changed minus stable team MAE | Team bias difference |','|---|---:|---:|']
 for y,v in r['seasons'].items():lines.append(f"| {y} | {v['difference_from_stable']['team_mae']:+.3f} | {v['difference_from_stable']['team_bias']:+.3f} |")
 lines+=['',f"Pooled team-MAE difference: +0.256, game-bootstrap 95% interval {r['changed_vs_stable']['difference_percentile95']['team_mae']}. Margin-MAE difference: +0.487, interval {r['changed_vs_stable']['difference_percentile95']['margin_mae']}. Both include zero. These are descriptive resampling intervals, not causal or multiplicity-adjusted tests.", '',
 'The team-MAE difference reverses sign in 2019, 2021 and 2022. Leave-one-season-out pooled differences remain positive, but season-openers reverse the association: changed 7.325 versus stable 8.110; within-season changed 7.883 versus stable 7.505. This does not meet a robust cross-season claim that starter changes always worsen accuracy.', '',
 'All favorite-size, week-band, roof, supported role, observed history, measured/unmeasured, exact-metadata and leave-one-season-out cells are in results.json. A mixed-role game can appear once in each applicable role table; those tables overlap and must not be summed. Both teams stay together within every bootstrap draw. Small primary-evidence cells are selected by source availability and cannot represent the whole population.', '',
 '| Sensitivity | Changed games | Stable games | Team-MAE difference |','|---|---:|---:|---:|']
 for k,v in extra.items():lines.append(f"| {k} | {v['games']} | {v['stable_baseline']['games']} | {v['difference_from_stable']['team_mae']:+.3f} |")
 lines+=['','## Independent review and remaining work','',
 'Independent code recomputed membership and all row errors directly from pinned schedule/control, verified seven producing source blobs, inspected primary sources and found alias and starter-definition defects. independent/check_ledger.py verifies all 2639 games, 660 unique changed sides, strict chronology and exact chart reconciliation after the fix. Independent full-table recomputation also passed all 47 comparisons, including 2,000 whole-game bootstrap intervals, with maximum numerical discrepancy 7.11e-15. All 10 seasonal coverage counts and 20 accepted publication bounds passed. This verifies arithmetic and qualified records, not completion of the remaining primary-source search.', '',
 'Remaining work is enumerated in remaining-evidence-queue.json: complete primary announcement/gamebook acquisition, resolve source disagreements, qualify pregame quality vintages, and locate external historical lock records if any exist. Do not register candidates or claim high causal confidence while these dimensions remain unresolved. The eventual intervention question is whether a qualified pregame QB representation improves authoritative forecasts beyond the existing strength inputs; no candidate is registered here.', '',
 'Confidence: medium for the narrower conclusion that these records do not yet distinguish identification failure from valuation failure—supported by authoritative data but dependent on defensible identity and timestamp choices. Downgrade to low if an independent archive establishes historical engine identities or changes the disputed source classifications. Confidence in a positive causal diagnosis is low: it could invert when the missing evidence is qualified. High confidence has not been earned.']
 (O/'REPORT.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':run()
