# Standalone bank-shaped fixture review

Accepted as a saved-state reconstruction for the narrow original `_bank_state_digest` interface, not as a runnable trajectory bank or new publication fixture. Read-only JSON/count/source inspection; no model imports, array construction, fit, scoring or digest execution.

Authenticated the641,244-byte accepted plain/origin-store/state-2013-01.json against the retained profile index: SHA `0be4fb5801dc501d6ebb0a15c764eac82a45edb81dc640db77c6ae2c626bbda1`. It contains297 distinct sorted tuple-convertible E3 keys,27 settings×11 variants;216 have own_state and81 have source_state. Each owned state has three32-element vectors, totaling20,736 exact JSON float leaves, all finite. No non-float conversion is needed. Reconstruct each owned vector with a fresh np.asarray(...,dtype=np.float64), preserving order, binary64 values and signed zeros; deepcopy every output. Use only the216 owned keys for bank.engines and all297 keys for outputs.

Original controller `_bank_state_digest` reads exactly sorted outputs and, for each sorted owned engine, last_origin plus ratings/offense/defense. A SimpleNamespace with these fields is sufficient for that function. last_origin is NOT explicitly stored in own_state. Its value `(2013,1)` follows the saved origin and accepted publish_origin check requiring every own engine last_origin equal the published season/week before state persistence. The original engine uses binary64 NumPy state vectors; publication canonicalizes them to JSON lists, so original dtype/strides/identity are not directly authenticated by the saved JSON. The proposed contiguous float64 reconstruction is an explicit derived fixture convention, not recovery of every original in-memory attribute.

No digest-required scalar or vector values are otherwise missing. A standalone reconstruction should separately assert exact key populations, vector field sets,32-length/finite/exact-float inputs, target/output order and metadata binding. Do not derive omitted engine state from scores or fit anything. The fixture cannot call publish_origin as a full bank: that path also requires engine.stored with target contexts and other source/view/assembly ownership evidence. stored, seen history, parameters, settings/stateful methods and mutable alias layout are not recovered here and are not needed by the digest function.

The original digest serializes values, not NumPy dtype/strides. Later snapshot-equivalence claims must specify whether they preserve original serialized equality versus a deliberately stricter typed relation; do not silently equate Python bool/int or ±0 or discard supported canonical conversions. This review supplies fixture eligibility only, no snapshot candidate/design or performance acceptance. All79 frozen sources remain unchanged; root retains all historical/research gates.
