import {chromium} from '/Users/gabe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[];fs.mkdirSync('work/board-v7/screenshots',{recursive:true});
for(const width of [360,390,1280]){const page=await browser.newPage({viewport:{width,height:width===390?844:900},reducedMotion:'reduce'});page.on('pageerror',e=>console.log('PAGEERROR',e.message));await page.goto('http://127.0.0.1:4177/work/board-v7/preview/index.html');await page.locator('.v7-row').first().waitFor();await page.screenshot({path:'work/board-v7/screenshots/points-final-'+width+'.png',fullPage:true});const ids=await page.locator('[data-game-id]').evaluateAll(xs=>xs.map(x=>x.dataset.gameId));if(await page.getByText('Football WHY').count())throw Error('Collapsed WHY');
const check=await page.locator('.v7-points-axis').evaluateAll(axes=>axes.flatMap(axis=>{const r=axis.getBoundingClientRect();return [...axis.querySelectorAll('[data-value]')].map(m=>{const value=Number(m.dataset.value),b=m.getBoundingClientRect();return Math.abs(b.x+b.width/2-r.x-Math.max(0,Math.min(45,value))/45*r.width)})}));if(Math.max(...check)>1)throw Error('Marker mapping');
await page.getByRole('button',{name:'ERROR',exact:true}).click();if(JSON.stringify(ids)!==JSON.stringify(await page.locator('[data-game-id]').evaluateAll(xs=>xs.map(x=>x.dataset.gameId))))throw Error('Order changed');await page.screenshot({path:'work/board-v7/screenshots/error-'+width+'.png',fullPage:true});
const geometry=await page.evaluate(()=>({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,viewport:innerHeight,rows:document.querySelectorAll('.v7-row').length}));if(geometry.width>width)throw Error('Horizontal overflow '+JSON.stringify(geometry));if(width===1280&&geometry.height>900)throw Error('Error slate scroll');
await page.locator('.v7-row').nth(2).click();await page.getByText('Football WHY').waitFor();if(await page.locator('.v7-detail [data-axis="POINTS"]').count()!==1)throw Error('Detail wrong axis');await page.screenshot({path:'work/board-v7/screenshots/expanded-'+width+'.png',fullPage:true});await page.locator('.v7-row').nth(3).click();if(await page.locator('.v7-detail').count()!==1)throw Error('Multiple expansions');
await page.goto('http://127.0.0.1:4177/work/board-v7/preview/index.html?upcoming');await page.locator('.v7-row').first().waitFor();await page.screenshot({path:'work/board-v7/screenshots/points-upcoming-'+width+'.png',fullPage:true});
await page.goto('http://127.0.0.1:4177/work/board-v7/preview/index.html?season');await page.getByRole('heading',{name:'Convergence',exact:true}).waitFor();await page.screenshot({path:'work/board-v7/screenshots/season-'+width+'.png',fullPage:true});const txt=await page.locator('body').innerText();if(await page.evaluate(()=>document.documentElement.scrollWidth)>width)throw Error('Season horizontal overflow');if(/\d+\.\d+/.test(txt))throw Error('Decimal text');await page.goto('http://127.0.0.1:4177/work/board-v7/preview/index.html?known');await page.locator('[data-value="20.25"]').waitFor();const fixture=await page.locator('[data-value="20.25"]').evaluate(m=>{const a=m.closest('.v7-axis').getBoundingClientRect(),r=m.getBoundingClientRect();return Math.abs(r.x+r.width/2-a.x-a.width*.45)});if(fixture>1)throw Error('Known fixture pixel position');await page.getByRole('button',{name:'ERROR',exact:true}).click();const outside=await page.locator('.v7-error-lane').first().evaluate(l=>{const d=l.querySelector('.v7-dot').getBoundingClientRect(),b=l.querySelector('[data-band="80"]').getBoundingClientRect();return d.x+d.width/2>b.right});if(!outside)throw Error('Outside dot inside band');results.push({width,known_fixture_pixel_error:fixture,marker_max_pixel_error:Math.max(...check),error_geometry:geometry});await page.close();}
fs.writeFileSync('work/board-v7/browser-check.json',JSON.stringify(results,null,2));await browser.close();
