# RF-COMP-01 synthetic qualification, version 1

The preceding turn was progress: accepted measured callback evidence retired insertion-only work and identified probability/serialization costs. This is a new computational candidate, preserving all 66 frozen scientific files and the terminal RF-02F identity. No historical data, archive admission, bootstrap, provider or production work.

One external parent observes one isolated child, limited to 60 seconds / 2,048 MiB including imports, source checks, unit tests, fixture setup and measurements. Persist the exact candidate/test/driver/scope bytes and hashes plus every process attempt, including failures. Stop at the first failed unit suite or numerical/equality assertion. Do not change the workload or remove a failing diagnostic to obtain a timing pass.

First run the focused suite against frozen SciPy/encoding/distribution/scorer oracles. Cover rates 1e-9, .01, .5, 1, 16, 22, 40, 100, 1000; scalar, array, negative, integer and fractional thresholds; signed zero, empty/noncontiguous arrays, unsupported dtypes/shapes/rates, huge integers, NaN/Inf and exceptions. Verify support masking avoids backend evaluation below zero. Check encoder bytes for empty and 700-element lists, signed zero, subnormal/exponent/extreme finite values, mixed/nested/unsupported values and nonfinite failures. Exercise correlated/independent laws, CDF/quantile/full-score bytes, invalid/ambiguous outcomes, memoization and copied-array isolation. The test source fixes the exact expanded case list before execution.

Only after all tests pass, compare the actual complete synthetic fitting/scoring pipeline in four modes: original, CDF-only, encoder-only, and both. Reuse the previous profile's fixed 3/700-atom constructions, actual tiny enhanced-Elo bank states, setting10 full/independent and setting6 zero-update variants, and observed fictional [21,17] under game ID z-target. Include full double grids and diagnostics in every score call. Each case has one warmup per mode and eight rounds with rotated four-mode order; retain all observations rather than choose favorable runs.

The actual `_Assembly.resolve` callback supplies the fit measurement. A harness-only binding selects `research_score_run.encoded` so both original descriptor creation and independent recovery use the proposed byte encoder; the frozen callback/check logic is unchanged. Restore that binding after each run. The real scorer wrapper supplies the full score callback; CDF modes use the candidate distribution with the unchanged metric implementation. Shipping code changes no shared module globals. Callback timing includes candidate guards, copies, encoding and calculation. Mode selection and equality hashing are outside timers, as are the original controller's native selection and post-callback persistence. Partial assembly setup bypasses constructor/archive admission explicitly.

Require every descriptor and full metric body to match original canonical bytes, and compare recovered law atoms, alpha, rates, theta, beta, independence and iterations exactly. Candidate grid/energy calculations are inherited unchanged; unit tests compare their actual values and byte behavior. Save original descriptor and metric bodies as well as hashes for independent review. CDF memoization remains local to each scorer call. No changes to solver, empirical arithmetic, Skellam/SF, failure guards, hash/authentication checks or scientific thresholds.

Interpret separate maxima within full-setting10 fit plus (a) two zero-update score controls, and (b) all full-flag stress scores. Report every mode's maxima, preparation-inclusive process cost, paired timing ranges, and unchanged/candidate ratios. The historical requirement remains F+S <=0.007461491790146312 seconds with other cost terms fixed, a 52.4680169716677 percent reduction from the retained actual pilot. Synthetic results can justify further engineering qualification, not a historical capacity claim, predictive claim or restart. Independent review must assess exactness, failures, resource evidence and timing interpretation before accepting a candidate. If measured whole-callback benefit is inadequate, stop or simplify before historical work.
